<style>
#tabs {    
    margin-left: auto;
    margin-right: auto;
    margin-top: 10px;
}
</style>
<div id="tabs">
    <ul>
        <li><a href="#tabs-1">By Season</a>
        </li>
        <li><a href="#tabs-2">By Holiday</a>
        </li>
        <li><a href="#tabs-3">By Occasion</a>
        
        <li><a href="#tabs-4">By Type</a>
        
        <li><a href="#tabs-5">By Theme</a>
        
        <li><a href="#tabs-6">By Brand</a>
        
        </li>
    </ul>
    <div id="tabs-1">    
     <!--tab-1 start-->
        <ul>
<li class="item first">
  <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?multi_seasons=4501" alt="Winter" title="Winter">
                       <img width="140" height="200" alt="Winter" src="{{skin url=images/widget/winter.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?multi_seasons=4501" alt="Winter" title="Winter">Winter</a>
                  </h5>
                </div>
</li>
<li class="item">
                <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?multi_seasons=4502" alt="Spring" title="Spring">
                       <img width="140" height="200" alt="Spring" src="{{skin url=images/widget/spring.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?multi_seasons=4502" alt="Spring" title="Spring">Spring</a>
                  </h5>
                </div>
</li>
<li class="item">
                <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?multi_seasons=4213" alt="Summer" title="Summer">
                       <img width="140" height="200" alt="Summer" src="{{skin url=images/widget/summer.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?multi_seasons=4213" alt="Summer" title="Summer">Summer</a>	</h5>
                </div>
</li> 
<li class="item last">
                <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?multi_seasons=4207" alt="Fall" title="Fall">
                       <img width="140" height="200" alt="Fall" src="{{skin url=images/widget/fall.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?multi_seasons=4207" alt="Fall" title="Fall">Fall</a>
                  </h5>
                </div>
</li>                                                  
</ul> 
 <!--tab-1 end-->

    </div>
    <div id="tabs-2">    
            <!--tab-2 start-->
         <ul>
<li class="item first">
                <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?holiday=4562" alt="Valentine's Day" title="Valentine's Day">
                       <img width="140" height="200" alt="Valentine's Day" src="{{skin url=images/widget/happy_valentines_day.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?holiday=4562" alt="Valentine's Day" title="Valentine's Day">Valentine's Day</a>
                  </h5>
                </div>
            </li>
            <li class="item">
                <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?holiday=4563" alt="Mardi Gras" title="Mardi Gras">
                       <img width="140" height="200" alt="Mardi Gras" src="{{skin url=images/widget/mardi_gras.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?holiday=4563" alt="Mardi Gras" title="Mardi Gras">Mardi Gras</a>
</h5>
                </div>
            </li>            
            <li class="item">
                <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?holiday=4564" alt="St. Patrick's Day" title="St. Patrick's Day">
                       <img width="140" height="200" alt="St. Patrick's Day" src="{{skin url=images/widget/happy_patricks.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?holiday=4564" alt="St. Patrick's Day" title="St. Patrick's Day">St. Patrick's Day</a>
                  </h5>
                </div>
            </li>
            <li class="item">
                <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?holiday=4565" alt="Easter" title="Easter">
                       <img width="140" height="200" alt="Easter" src="{{skin url=images/widget/easter.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?holiday=4565" alt="Easter" title="Easter">Easter</a>
                  </h5>
                </div>
            </li>
		 <li class="item">
                <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?holiday=4566" alt="Mother's Day" title="Mother's Day">
                       <img width="140" height="200" alt="Mother's Day" src="{{skin url=images/widget/happy_mothers_day.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?holiday=4566" alt="Mother's Day" title="Mother's Day">Mother's Day</a>	</h5>
                </div>
            </li>  
           <li class="item">
                <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?holiday=4574" alt="Memorial Day" title="Memorial Day">
                       <img width="140" height="200" alt="Memorial Day" src="{{skin url=images/widget/memorial_day.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?holiday=4574" alt="Memorial Day" title="Memorial Day">Memorial Day</a></h5>
                </div>
            </li>
 <li class="item">
                <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?holiday=4567" alt="Father's Day" title="Father's Day">
                       <img width="140" height="200" alt="Father's Day" src="{{skin url=images/widget/happy_fathers_day.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?holiday=4567" alt="Father's Day" title="Father's Day">Father's Day</a>
                  </h5>
                </div>
            </li>  
           <li class="item">
                <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?holiday=4568" alt="4th of July" title="4th of July">
                       <img width="140" height="200" alt="4th of July" src="{{skin url=images/widget/4th_of_july.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?holiday=4568" alt="4th of July" title="4th of July">4th of July</a>
                  </h5>
                </div>
            </li> 
             <li class="item">
                <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?holiday=4569" alt="Halloween" title="Halloween">
                       <img width="140" height="200" alt="Halloween" src="{{skin url=images/widget/halloween.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?holiday=4569" alt="Halloween" title="Halloween">Halloween</a>
                  </h5>
                </div>
            </li>
             <li class="item">
                <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?holiday=4570" alt="Thanksgiving" title="Thanksgiving">
                       <img width="140" height="200" alt="Thanksgiving" src="{{skin url=images/widget/thanksgiving.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?holiday=4570" alt="Christmas" title="Christmas">Thanksgiving</a>
                  </h5>
                </div>
            </li>
             <li class="item">
                <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?holiday=4571" alt="Christmas" title="Christmas">
                       <img width="140" height="200" alt="Thanksgiving" src="{{skin url=images/widget/chrismas.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?holiday=4571" alt="Christmas" title="Christmas">Christmas</a>
                  </h5>
                </div>
            </li> 
              <li class="item">
                <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?holiday=4572" alt="Hanukkah" title="Hanukkah">
                       <img width="140" height="200" alt="Hanukkah" src="{{skin url=images/widget/hannukah.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?holiday=4572" alt="Hanukkah" title="Hanukkah">Hanukkah</a>
                  </h5>
                </div>
            </li>                                                  
		</ul> 
         <!--tab-2 end-->
    </div>
    <div id="tabs-3">
        <!--tab-3 start-->
        <ul>
<li class="item first">
  <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?occassion=4554" alt="Anniversary" title="Anniversary">
                       <img width="140" height="200" alt="Anniversary" src="{{skin url=images/widget/anniversary.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?occassion=4554" alt="Anniversary" title="Anniversary">Anniversary</a>
                  </h5>
                </div>
</li>
<li class="item">
                <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?occassion=4555" alt="Baby & Kids" title="Baby & Kids">
                       <img width="140" height="200" alt="Baby & Kids" src="{{skin url=images/widget/baby_kids.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?occassion=4555" alt="Baby & Kids" title="Baby & Kids">Baby & Kids</a>
                  </h5>
                </div>
</li>
<li class="item">
                <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?occassion=4556" alt="Birthday" title="Birthday">
                       <img width="140" height="200" alt="Birthday" src="{{skin url=images/widget/birthday.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?occassion=4556" alt="Birthday" title="Birthday">Birthday</a>	</h5>
                </div>
</li> 
<li class="item">
                <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?occassion=4557" alt="Wedding" title="Wedding">
                       <img width="140" height="200" alt="Wedding" src="{{skin url=images/widget/wedding.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?occassion=4557" alt="Wedding" title="Wedding">Wedding</a>
                  </h5>
                </div>
</li>
<li class="item">
                <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?occassion=4558" alt="Grandparents" title="Grandparents">
                       <img width="140" height="200" alt="Grandparents" src="{{skin url=images/widget/grandparents.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?occassion=4558" alt="Grandparents" title="Grandparents">Grandparents</a>
                  </h5>
                </div>
</li>                                                  
<li class="item">
                <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?occassion=4559" alt="Friends" title="Friends">
                       <img width="140" height="200" alt="Friends" src="{{skin url=images/widget/friends.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?occassion=4559" alt="Friends" title="Friends">Friends</a>
                  </h5>
                </div>
</li> 
<li class="item">
                <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?occassion=4560" alt="Family" title="Family">
                       <img width="140" height="200" alt="Family" src="{{skin url=images/widget/family.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?occassion=4560" alt="Family" title="Family">Family</a>
                  </h5>
                </div>
</li>
<li class="item">
                <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?occassion=4561" alt="Cemetery" title="Cemetery">
                       <img width="140" height="200" alt="Cemetery" src="{{skin url=images/widget/cemetery.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?occassion=4561" alt="Cemetery" title="Cemetery">Cemetery</a>
                  </h5>
                </div>
</li>                                                      
<li class="item">
                <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?occassion=4552" alt="Graduation" title="Graduation">
                       <img width="140" height="200" alt="Graduation" src="{{skin url=images/widget/graduation.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?occassion=4552" alt="Graduation" title="Graduation">Graduation</a>
                  </h5>
                </div>
</li>                                                      
<li class="item">
                <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?occassion=4553" alt="Back to School" title="Back to School">
                       <img width="140" height="200" alt="Back to School" src="{{skin url=images/widget/back_to_school.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?occassion=4553" alt="Back to School" title="Back to School">Back to School</a>
                  </h5>
                </div>
</li>  
</ul> 
        <!--tab-3 end-->
    </div>
    <div id="tabs-4">
         <!--tab-4 start-->
         <!--tab-4 end-->
    </div>
    <div id="tabs-5">
        <!--tab-5 start-->
        <ul>
<li class="item first">
  <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?multi_themes=4482" alt="Beaches & Nautical" title="Beaches & Nautical">
                       <img width="140" height="200" alt="Beaches & Nautical" src="{{skin url=images/widget/beaches-nautical.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?multi_themes=4482" alt="Beaches & Nautical" title="Beaches & Nautical">Beaches & Nautical</a>
                  </h5>
                </div>
</li>
<li class="item">
                <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?multi_themes=4476" alt="Birds & Birdhouses" title="Birds & Birdhouses">
                       <img width="140" height="200" alt="Birds & Birdhouses" src="{{skin url=images/widget/birds_birdhouses.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?multi_themes=4476" alt="Birds & Birdhouses" title="Birds & Birdhouses">Birds & Birdhouses</a>
                  </h5>
                </div>
</li>
<li class="item">
                <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?multi_themes=4484" alt="Butterflies & Insects" title="Butterflies & Insects">
                       <img width="140" height="200" alt="Butterflies & Insects" src="{{skin url=images/widget/butterflies-insects.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?multi_themes=4484" alt="Butterflies & Insects" title="Butterflies & Insects">Butterflies & Insects</a>	</h5>
                </div>
</li> 
<li class="item">
                <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?multi_themes=4483" alt="Family & Friends" title="Family & Friends">
                       <img width="140" height="200" alt="Family & Friends" src="{{skin url=images/widget/family-friends.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?multi_themes=4483" alt="Family & Friends" title="Family & Friends">Family & Friends</a>
                  </h5>
                </div>
</li>
<li class="item">
                <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?multi_themes=4478" alt="Flowers & Gardens" title="Flowers & Gardens">
                       <img width="140" height="200" alt="Flowers & Gardens" src="{{skin url=images/widget/flowers-gardens.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?multi_themes=4478" alt="Flowers & Gardens" title="Flowers & Gardens">Flowers & Gardens</a>
                  </h5>
                </div>
</li>                                                  
<li class="item">
                <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?multi_themes=4474" alt="Food & Wine" title="Food & Wine">
                       <img width="140" height="200" alt="Food & Wine" src="{{skin url=images/widget/food-wine.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?multi_themes=4474" alt="Food & Wine" title="Food & Wine">Food & Wine</a>
                  </h5>
                </div>
</li> 
<li class="item">
                <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?multi_themes=4480" alt="For The Cause" title="For The Cause">
                       <img width="140" height="200" alt="For The Cause" src="{{skin url=images/widget/for-the-cause.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?multi_themes=4480" alt="For The Cause" title="For The Cause">For The Cause</a>
                  </h5>
                </div>
</li>
<li class="item">
                <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?multi_themes=4479" alt="Great Outdoors" title="Great Outdoors">
                       <img width="140" height="200" alt="Great Outdoors" src="{{skin url=images/widget/great-outdoors.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?multi_themes=4479" alt="Great Outdoors" title="Great Outdoors">Great Outdoors</a>
                  </h5>
                </div>
</li>                                                      
<li class="item">
                <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?multi_themes=4473" alt="Love & Happiness" title="Love & Happiness">
                       <img width="140" height="200" alt="Love & Happiness" src="{{skin url=images/widget/love-happiness.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?multi_themes=4473" alt="Love & Happiness" title="Love & Happiness">Love & Happiness</a>
                  </h5>
                </div>
</li>                                                      
<li class="item">
                <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?multi_themes=4472" alt="Monogrammed" title="Monogrammed">
                       <img width="140" height="200" alt="Monogrammed" src="{{skin url=images/widget/monogrammed.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?multi_themes=4472" alt="Monogrammed" title="Monogrammed">Monogrammed</a>
                  </h5>
                </div>
</li>  
<li class="item">
                <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?multi_themes=4465" alt="Open & Sale" title="Open & Sale">
                       <img width="140" height="200" alt="Open & Sale" src="{{skin url=images/widget/open-sale.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?multi_themes=4465" alt="Open & Sale" title="Open & Sale">Open & Sale</a>
                  </h5>
                </div>
</li>  
<li class="item">
                <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?multi_themes=4481" alt="Party Time" title="Party Time">
                       <img width="140" height="200" alt="Party Time" src="{{skin url=images/widget/Party Time.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?multi_themes=4481" alt="Party Time" title="Party Time">Party Time</a>
                  </h5>
                </div>
</li>
<li class="item">
                <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?multi_themes=4466" alt="Patriotic & Military" title="Patriotic & Military">
                       <img width="140" height="200" alt="Patriotic & Military" src="{{skin url=images/widget/patriotic-military.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?multi_themes=4466" alt="Patriotic & Military" title="Patriotic & Military">Patriotic & Military</a>
                  </h5>
                </div>
</li>    
<li class="item">
                <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?multi_themes=4477" alt="Patterns" title="Patterns">
                       <img width="140" height="200" alt="Patterns" src="{{skin url=images/widget/patterns.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?multi_themes=4477" alt="Patterns" title="Patterns">Patterns</a>
                  </h5>
                </div>
</li>   
<li class="item">
                <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?multi_themes=4464" alt="Pets & Animals" title="Pets & Animals">
                       <img width="140" height="200" alt="Pets & Animals" src="{{skin url=images/widget/pets-animals.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?multi_themes=4464" alt="Pets & Animals" title="Pets & Animals">Pets & Animals</a>
                  </h5>
                </div>
</li>   
<li class="item">
                <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?multi_themes=4467" alt="Primitive & Americana" title="Primitive & Americana">
                       <img width="140" height="200" alt="Primitive & Americana" src="{{skin url=images/widget/primitive-americana.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?multi_themes=4467" alt="Primitive & Americana" title="Primitive & Americana">Primitive & Americana</a>
                  </h5>
                </div>
</li>   
<li class="item">
                <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?multi_themes=4468" alt="Regional" title="Regional">
                       <img width="140" height="200" alt="Regional" src="{{skin url=images/widget/regional.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?multi_themes=4468" alt="Regional" title="Regional">Regional</a>
                  </h5>
                </div>
</li>  
<li class="item">
                <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?multi_themes=4469" alt="Religious" title="Religious">
                       <img width="140" height="200" alt="Religious" src="{{skin url=images/widget/religious.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?multi_themes=4469" alt="Religious" title="Religious">Religious</a>
                  </h5>
                </div>
</li>    
<li class="item">
                <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?multi_themes=4470" alt="Sports & Recreation" title="Sports & Recreation">
                       <img width="140" height="200" alt="Sports & Recreation" src="{{skin url=images/widget/sports-recreation.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?multi_themes=4470" alt="Sports & Recreation" title="Sports & Recreation">Sports & Recreation</a>
                  </h5>
                </div>
</li> 
<li class="item">
                <div class="featuredcategory-image">
                    <a href="http://flagsrus.stripedsocks.com/filter.html?multi_themes=4471" alt="Welcome" title="Welcome">
                       <img width="140" height="200" alt="Welcome" src="{{skin url=images/widget/welcome.png}}">
                    </a>
                </div>
                <div style="width:200px" class="featuredcategory-name">
                  <h5>
               <a target="_blank" href="http://flagsrus.stripedsocks.com/filter.html?multi_themes=4471" alt="Welcome" title="Welcome">Welcome</a>
                  </h5>
                </div>
</li> 
</ul> 
        
         <!--tab-5 end-->
    </div>
    <div id="tabs-6">
        <!--tab-6 start-->
         <!--tab-6 end-->
    </div>
</div>
<script>
jQuery("#tabs").tabs({
    activate: function (event, ui) {
        var active = jQuery('#tabs').tabs('option', 'active');
        jQuery("#tabid").html('the tab id is ' + jQuery("#tabs ul>li a").eq(active).attr("href"));

    }
}

);
</script>