<?php

/**
 * Featured Products Slider
 */

?>

<?php

$_productCollection = $this->getLoadedProductCollection ();

?>

<?php if ($_productCollection && ($_collectionSize = $this->getCollectionCount ())): ?>

    <?php

    $_helper = $this->helper ('catalog/output');

    $theme = $this->helper ('ultimo');

    $helpLabels = $this->helper ('ultimo/labels');

    $helpTemplate = $this->helper ('ultimo/template');

    $helpImg = $this->helper ('infortis/image');

    $sliderClasses = '';

    $gridClasses = '';

    $hash = $this->getFrontendHash ();

    $sliderId = "itemslider-featured-{$hash}";

    //Slider parameters

    //--------------------------------------------------------------

    //Responsive mode on/off

    $isResponsive = $this->getIsResponsive (); //param: is_responsive

    if ($isResponsive === NULL) //Param not set

    {

        $isResponsive = TRUE; //IMPORTANT: enabled by default

    }

    //Assign number of items in a row to specific viewport width

    $breakpoints = $this->getBreakpoints (); //param: breakpoints

    if ($breakpoints === NULL) //Param not set

    {

        $breakpoints = '[0, 1], [320, 2], [480, 3], [768, 4], [960, 4], [1280, 4]'; //Set default breakpoints

    }

    //Number of items in a row displayed if responsive mode is off

    $showItems = $this->getShowItems (); //param: show_items

    if (!$showItems) //Param not set or equals zero

    {

        $showItems = 5; //Set default number of items

    }

    //Pagination on/off

    $pagination = $this->getPagination (); //param: pagination

    //Slider initial delay

    $initDelay = 0;

    $initDelay = intval ($this->getInitDelay ()); //param: init_delay

    //Image width

    $imgWidth = $this->getImgWidth (); //param: img_width

    if ($imgWidth === NULL) //Param not set

    {

        $imgWidth = 196; //Set default value

    } else {

        $imgWidth = intval ($imgWidth);

    }

    //Image aspect ratio

    if ($theme->getCfg ('category/aspect_ratio')) {

        $imgHeight = 0; //Keep aspect ratio - height will be calculated automatically based on width

    } else {

        $imgHeight = $imgWidth; //Don't keep aspect ratio - height is the same as width

    }

    //Image height

    if ($this->getImgHeight () !== NULL) //param: img_height

    {

        //If param is set, it overrides default height and aspect ratio settings

        $imgHeight = intval ($this->getImgHeight ());

    }

    //Slider timeout. Set to enable automatic scrolling.

    $timeout = $this->getTimeout (); //param: timeout

    if ($timeout === NULL) //Param not set

    {

        $timeout = intval ($theme->getCfg ('product_slider/timeout'));

    } else {

        $timeout = intval ($timeout);

    }

    //Number of items that should move on scrolling

    $move = $this->getMove (); //param: move

    if ($move === NULL) //Param not set

    {

        $move = 0; //By default scroll all visible items

    } else {

        $move = intval ($move);

    }

    //If set, slider will loop

    $loop = $this->getLoop (); //param: loop

    if ($loop === NULL) //Param not set

    {

        $loop = $theme->getCfg ('product_slider/loop');

    }

    //Speed (arrows / touch swipe)

    $speed = intval ($theme->getCfg ('product_slider/speed'));

    //Speed (automatic scrolling / pagination)

    $autoSpeed = intval ($theme->getCfg ('product_slider/auto_speed'));

    //Pause slider on mouse hover

    $pause = $theme->getCfg ('product_slider/pause');

    //Lazy loading

    $lazy = $theme->getCfg ('product_slider/lazy');

    //Slider classes

    //--------------------------------------------------------------

    if ($isResponsive) {

        $sliderClasses .= ' itemslider-responsive';

    }

    if ($_collectionSize == 1) {

        $sliderClasses .= ' single-item';

    }

    //Product grid classes

    //--------------------------------------------------------------

    //Size of grid elements

    $size = $this->getSize (); //param: size

    if ($size) {

        $gridClasses = ' ' . $size;

    } else {

        if ($showItems >= 8) {

            $gridClasses = ' size-xs';

        } elseif ($showItems >= 6) {

            $gridClasses = ' size-s';

        }

    }

    //Align elements to the center

    if ($this->getCentered ()) //param: centered

    {

        $gridClasses .= ' centered';

    }

    //Set equal height for all items

    if ($this->getEqualHeight ()) //param: equal_height

    {

        $gridClasses .= ' equal-height';

    }

    ?>

    <?php /* $sa_reviews = "<script type='text/javascript'> function saLoadScript(src) { var js = window.document.createElement('script'); js.src = src; js.type = 'text/javascript'; document.getElementsByTagName('head')[0].appendChild(js); } saLoadScript('//www.shopperapproved.com/widgets/group2.0/12756.js'); </script>";
    echo $sa_reviews; */
    ?>
    <div class="page-title">
        <h3 class="section-title"><?php echo $this->getBlockName (); ?></h3>
    </div>

    <div class="itemslider-wrapper slider-arrows1 slider-arrows1-pos-top-right slider-pagination1">

        <div id="<?php echo $sliderId; ?>"
             class="products-grid category-products-grid itemgrid itemgrid-adaptive centered hover-effect equal-height itemslider<?php if ($sliderClasses) echo $sliderClasses; ?> products-grid<?php if ($gridClasses) echo $gridClasses; ?>">

            <?php foreach ($_productCollection as $_product): ?>

                <div class="item" id="<?php echo $_product->getId (); ?>">


                    <div class="product-image-wrapper" style="max-width:<?php echo $imgWidth; ?>px;">


                        <a href="<?php echo $_product->getProductUrl () ?>"
                           title="<?php echo $this->stripTags ($this->getImageLabel ($_product, 'small_image'), NULL, TRUE); ?>"
                           class="product-image">


                            <?php if ($lazy): ?>

                                <img class="owl-lazy"
									 data-src="<?php echo $helpImg->getImg ($_product, $imgWidth, $imgHeight, 'small_image'); ?>"
                                     alt="<?php echo $this->stripTags ($this->getImageLabel ($_product, 'small_image'), NULL, TRUE); ?>"/>

                            <?php else: ?>

                                <img
                                    src="<?php echo $helpImg->getImg ($_product, $imgWidth, $imgHeight, 'small_image'); ?>"
                                    alt="<?php echo $this->stripTags ($this->getImageLabel ($_product, 'small_image'), NULL, TRUE); ?>"/>

                            <?php endif; ?>



                            <?php if ($theme->getCfg ('category/alt_image')): ?>

                                <?php echo $theme->getAltImgHtml ($_product, $imgWidth, $imgHeight); ?>

                            <?php endif; ?>



						<?php //echo $helpLabels->getLabels ($_product); //Product labels ?>
						<?php if($_product->getIconlabel()!=''): ?>
							<span class="sticker-wrapper top-left"><span class="sticker new"><?php echo $_product->getIconlabel(); ?></span></span>
						<?php endif; ?>

                        </a>


                        <?php //Add-to links

                        if ($theme->getCfg ('category_grid/display_addtolinks') != 0

                            && $theme->getCfg ('category_grid/addtolinks_simple')
                        ) {

                            if ($theme->getCfg ('category_grid/display_addtolinks') == 1) //Display on hover

                            {

                                echo $helpTemplate->getCategoryAddtoLinksIcons (

                                    $_product, $this->getAddToCompareUrl ($_product), 'addto-links-icons addto-onimage visible-onhover');

                            } else //Always display

                            {

                                echo $helpTemplate->getCategoryAddtoLinksIcons (

                                    $_product, $this->getAddToCompareUrl ($_product), 'addto-links-icons addto-onimage');

                            }

                        }

                        ?>


                    </div>
                    <!-- end: product-image-wrapper -->


                    <h3 class="product-name"><a href="<?php echo $_product->getProductUrl () ?>"
                                                title="<?php echo $this->stripTags ($_product->getName (), NULL, TRUE) ?>"><?php echo $_helper->productAttribute ($_product, $_product->getName (), 'name') ?></a>
                    </h3>

                    <?php if ($_product->getRatingSummary ()): ?>

                        <?php echo $this->getReviewsSummaryHtml ($_product, 'short') ?>

                    <?php endif; ?>

                    <?php echo $this->getPriceHtml ($_product, TRUE, $hash) ?>

                    <div class="actions">


                        <?php if (!$this->getHideButton ()): ?>

                            <?php if (!$_product->canConfigure () && $_product->isSaleable ()): ?>

                                <!--=================== by brt =================-->
                                <?php
                                $stock = Mage::getModel('cataloginventory/stock_item')->loadByProduct($_product);
                                $productCount=intval($stock->getQty());
                                ?>
                                <!--=================== by brt ends =================-->

<!--                                <input type="text" class="input-text qty" title="Qty" value="0" maxlength="12" id="qty" name="qty">-->
                                <!--=================== by brt =================-->
                            <?php $cartUrl = Mage::helper('checkout/cart')->getAddUrl($_product); ?>
                             <form action="<?php echo $cartUrl; ?>" method="post" class="product_addtocart_form product_addtocart_form_<?php echo $_product->getSku(); ?>" name="product_addtocart_form<?php echo $_product->getId(); ?>" id="product_addtocart_form<?php echo $_product->getId(); ?>"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
                            <?php echo $this->getBlockHtml('formkey'); ?>
                             <!--input type="hidden" name="qty" value="1"-->
                            <input type="hidden" id="<?php echo $_product->getSku()."-addtourl"; ?>" name="addtourl" value="<?php echo $cartUrl;?>">
                            <input type="hidden" name="product" value="<?php echo $_product->getId();?>">
                            <input type="hidden" name="related_product" value="">
                            <input type="hidden" name="return_url" value="">
                                <div class="<?php echo $_product->getSku()."-addto"; ?>">
									<select class="input-text qty" name="qty" id="qty">
										<?php $i = 1 ?>
										<?php do { ?>
											<option value="<?php echo $i?>">
												<?php echo $i?>
												<?php $i++ ?>
											</option>
										<?php } while ($i <= $productCount) ?>
									</select>
									<!--=================== by brt ends =================-->
									
									   <!--button type="button" title="<?php echo $this->__ ('Add to Cart') ?>"
											class="button btn-cart"
											onclick="setLocation('<?php echo $this->getAddToCartUrl ($_product) ?>')"><span><span><?php echo $this->__ ('Add to Cart') ?></span></span>
										</button-->
									<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart <?php echo $_product->getSku()."-del"; ?>" id="" onclick="ajaxaddtocart.ajaxCartSubmit(productAddToCartForm<?php echo $_product->getId(); ?>);"><span><i class="icon ic ic-bag"></i><span><?php echo $this->__('Add to Cart') ?></span></span></button>
								</div>
								<div class="<?php echo $_product->getSku()."-addremove"; ?>" style="display:none;">
									<button type="button" title="<?php echo $this->__('Add/Remove') ?>" class="button btn-cart add-remove" onclick="ajaxaddtocart.ajaxCartSubmit(productAddToCartForm<?php echo $_product->getId(); ?>);"><span><span><?php echo $this->__('Add/Remove') ?></span></span></button>
								</div>
                                </form>
                        <script type="text/javascript">
                                //<![CDATA[
                                var productAddToCartForm<?php echo $_product->getId(); ?> = new VarienForm('product_addtocart_form<?php echo $_product->getId(); ?>');
                                //]]>
                        </script>
                            <?php elseif ($_product->getStockItem () && $_product->getStockItem ()->getIsInStock ()): ?>

                                <a title="<?php echo $this->__ ('See Options') ?>" class="button btn-cart"
                                   href="<?php echo $_product->getProductUrl () ?>"><?php echo $this->__ ('See Options') ?></a>

                            <?php else: ?>

                                <p class="availability out-of-stock">
                                    <span><?php echo $this->__ ('Out of stock') ?></span></p>

                            <?php endif; ?>

                        <?php endif; ?>



                        <?php //Add-to links

                        if ($theme->getCfg ('category_grid/display_addtolinks') != 0 && !$theme->getCfg ('category_grid/addtolinks_simple')) {

                            if ($theme->getCfg ('category_grid/display_addtolinks') == 1) //Display on hover

                                echo $helpTemplate->getCategoryAddtoLinks ($_product, $this->getAddToCompareUrl ($_product), 'addto-gaps-right addto-texticons display-onhover');

                            else //Always display

                                echo $helpTemplate->getCategoryAddtoLinks ($_product, $this->getAddToCompareUrl ($_product), 'addto-gaps-right addto-texticons');

                        }

                        ?>


                    </div>
                    <div class="clearer"></div>
                    <?php $getId = $_product->getId (); ?>
                    <?php $getIdcls = "rating-and-qty-block" . $_product->getId (); ?>
                    <div class="rating-and-qty-block  <?php echo $getIdcls; ?>"><!-- start: rating-and-qty-block-->
                        <!--div class="ratings"> <!-- start: ratings >
                            <div class="star_container <?php echo Mage::getModel ('catalog/product')
                                ->load ($_product->getId ())->getSku (); ?>"></div>
                        </div-->
                        <!-- end: ratings -->
                        <div class="qty-in-stock"><!-- start: Qty in stock -->
                            <?php
                            $stock = Mage::getModel ('cataloginventory/stock_item')->loadByProduct ($_product);
                            echo $this->__ ("Qty in Stock: ") . intval ($stock->getQty ());
                            ?>
                        </div>
                        <!-- end: Qty in stock -->

                    </div>
                    <!-- end: rating-and-qty-block-->


                </div>

            <?php endforeach; ?>

        </div>
        <!-- end: itemslider -->

    </div> <!-- end: itemslider-wrapper -->

    <script type="text/javascript">

        //<![CDATA[

        jQuery(function ($) {


            var owl = $('#<?php echo $sliderId; ?>');

            owl.owlCarousel({


                <?php if ($lazy): ?>

                lazyLoad: true,

                <?php endif; ?>

                 

                <?php if(!$isResponsive): ?>

                responsive: false,

                //items: <?php echo $showItems; ?>,

                <?php else: ?>

                //itemsCustom: [<?php echo $breakpoints; ?>],
                 responsiveClass:true,
                 responsive: {0:{items:1},480:{items:2},960:{items:4}},

                responsiveRefreshRate: 50,

                <?php endif; ?>



                <?php if ($speed): ?>

                slideSpeed: <?php echo $speed; ?>,

                <?php endif; ?>



                <?php if ($autoSpeed): ?>

                paginationSpeed: <?php echo $autoSpeed; ?>,

                <?php endif; ?>



                <?php if ($move !== 1): ?>

                scrollPerPage: true,

                <?php endif; ?>



                <?php if ($timeout): ?>

                autoPlay: <?php echo $timeout; ?>,

                <?php endif; ?>



                <?php if ($pause): ?>

                stopOnHover: true,

                <?php endif; ?>



                <?php if ($loop): ?>

                loop: true,

                rewindSpeed: 600,

                <?php else: ?>

                rewindNav: false,

                <?php endif; ?>



                <?php if ($pagination): ?>

                pagination: true,

                <?php else: ?>

                pagination: false,

                <?php endif; ?>



                nav: true,

                navigationText: false


            }); //end: owl


        });

        //]]>

    </script>

<?php endif; ?>
<script type="text/javascript">
    jQuery(document).ready(function () {
        if (jQuery(window).width() > 768) {
            jQuery(".rating-and-qty-block").hide();
            jQuery('.products-grid  .item').on('mouseover', function () {
                var pid = jQuery(this).attr('id');
                //alert(pid);
                jQuery('.rating-and-qty-block' + pid).show();
            }).on('mouseout', function () {
                var pid = jQuery(this).attr('id');
                jQuery('.rating-and-qty-block' + pid).hide();
            });
        } else {

            jQuery(".rating-and-qty-block").show();
        }
    });
</script>
