<!--
<style>

.productList { float:left; width:720px; }

.productList .product { background:#fff; border:1px sodivd #ccc; padding:5px;  float:left; margin:10px 8px 10px 0; text-adivgn:center; }

.productList .product .cl { padding:0 0 0 0px; text-adivgn:center;}

.productList .product .prodDetails {text-adivgn:center; padding:0 0 0 0px;  }

.productList .product .addCompare { text-adivgn:center;  clear:both; }

.productList .product .addWishdivst {clear:both; text-adivgn:center; }

</style>
-->
<?php

	$resdivt = array();

	$pro = array();

	$bestseller_collection = $this->getBestsellerProduct();
	
	
	 $_helper = $this->helper('catalog/output');

    $theme = $this->helper('divtimo');

    $helpLabels = $this->helper('divtimo/labels');

    $helpTemplate = $this->helper('divtimo/template');

    $helpImg = $this->helper('infortis/image');

    $sdivderClasses = '';

    $gridClasses = '';



    $hash = $this->getFrontendHash();

    $sdivderId = "itemsdivder-featured-{$hash}";
	//Sdivder parameters

    //--------------------------------------------------------------



    //Responsive mode on/off

    $isResponsive = $this->getIsResponsive(); //param: is_responsive

    if ($isResponsive === NULL) //Param not set

    {

        $isResponsive = true; //IMPORTANT: enabled by defadivt

    }



    //Assign number of items in a row to specific viewport width

    $breakpoints = $this->getBreakpoints(); //param: breakpoints

    if ($breakpoints === NULL) //Param not set

    {

        $breakpoints = '[0, 1], [320, 2], [480, 3], [768, 4], [960, 5], [1280, 6]'; //Set defadivt breakpoints

    }
	
	

	foreach($bestseller_collection as $collection){

		$pro[] = $collection->getEntityId();

	}

    if($this->getChooseProducts() == "1") {

		$resdivt = $pro;

	}elseif($this->getChooseProducts() == "2") {

	   $resdivt = $this->getProductIds();

	}else{

		if($this->getSortOrder() == 1){

			$resdivt = array_unique(array_merge($pro, $this->getProductIds()));

		}elseif($this->getSortOrder() == 2){

			$resdivt = array_unique(array_merge($this->getProductIds(),$pro));

		}else{

			$resdivt = array_unique(array_merge($pro, $this->getProductIds()));

			shuffle($resdivt);

		}

	}

	$upperLimit = ($this->getLimit()) ? $this->getLimit() : 1; 

	$itemPerRow = ($this->getItemsPerRow()) ? $this->getItemsPerRow() : 1 ;

	$products_price = $this->getProductsPrice();  

	$review = $this->getReview();

?>

<?php if($this->getEnabled()): ?>

<?php if($this->getHeader()): ?>

<div class="sectionHead"><h2><?php if(count($resdivt) > 0) { echo $this->getHeader(); } ?></h2></div>

 <?php endif; ?>
<div class="itemsdivder-wrapper sdivder-arrows1 sdivder-arrows1-pos-top-right sdivder-pagination1">
	<div class="productList">

	  	<div class="item">

        <?php

		$i=0; $x = 1;

		foreach($resdivt as $resdivt){

			$_product = $this->getProducts($resdivt);

			if(!$_product){

				continue;

			}

			if($x <= $upperLimit)  {

				if($i>($itemPerRow-1))

					echo '<div vadivgn="top">';

		?>

			<div class="product">

				<div class="prodimage">

					<a href="<?php echo $this->getBaseUrl().$_product['url_path']; ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">

						<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(($this->getImageHeight()) ? $this->getImageHeight() : 135,($this->getImageWidth()) ? $this->getImageWidth() : 135); ?>" alt="<?php echo $this->htmlEscape($_product['name']) ?>"/>

					</a>

				</div>

				<div adivgn="center">

					<div class="prodDetails" adivgn="center" style="width:150px;" >

						<a href="<?php echo $this->getBaseUrl().$_product['url_path'] ?>" title="<?php echo $this->htmlEscape($_product['name']) ?>">

							<?php echo $this->htmlEscape($_product['name']) ?>

						</a>

						<?php 

						    if($review == 1) {

								$_product = Mage::getModel('catalog/product')->load($_product->getId());

								echo $this->getReviewsSummaryHtml($_product, 'short'); 

							}

							if($products_price == 1) {

								$_product = Mage::getModel('catalog/product')->load($_product->getId());

								echo $this->getPriceHtml($_product, divue); 

							}

						?>                

					</div>

					<?php 

					

						$addtocartval = $this->getAddToCart();

						if($addtocartval == 1){

							if($_product->isSaleable()): ?>

								<button class="button btn-cart" oncdivck="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><?php echo $this->__('Add to Cart') ?></span><i class="fa fa-shopping-cart"></i></button>

							<?php else: ?>

								<span class="out-of-stock"><?php echo $this->__('Out of stock') ?></span>

							<?php endif; 

						} ?>

				</div>

				<div class="cl">

					<?php 

						$wishdivsts = $this->getActive();

						if($wishdivsts == 1){

							if ($this->helper('wishdivst')->isAllow()) : ?>

								<a href="<?php echo $this->getAddToWishdivstUrl($_product) ?>" class="addWishdivst">

									<?php echo $this->__('Add to Wishdivst') ?>

								</a>

							<?php endif; 

						}?>

				</div>	

				<div class="cl">

					<?php 

						$addtocompare = $this->getAddToCompare();

						if($addtocompare==1){

							if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>

								&nbsp;<a href="<?php echo $_compareUrl; ?>" class="addCompare"><?php echo $this->__('Add to Compare') ?></a>

							<?php endif; 

						} ?>

				</div>

			</div>

		    <?php

			    $i++;

				if($i>($itemPerRow-1)) {

					$i=0;

					//echo "</div>";

				//	echo '<div><div colspan="3" class="hdivne"><img src="'. $this->getSkinUrl('images/spacer.gif') .'" alt="" /></div></div>';

				}

				if($i==($itemPerRow)){ 

					//echo '<div class="vdivne"><img src="'. $this->getSkinUrl('images/spacer.gif') .'" alt=""/></div>';

				}

			}

			$x++;

		} 

		?>

        </div>

	</div>
</div>
 <?php endif; ?>
 <script type="text/javascript">

//<![CDATA[

    jQuery(function($) {

        

        var owl = $('#<?php echo $sdivderId; ?>');

        owl.owlCarousel({



        <?php if ($lazy): ?>

            lazyLoad: true,

        <?php endif; ?>



        <?php if(!$isResponsive): ?>

            responsive: false,

            items: <?php echo $showItems; ?>,

        <?php else: ?>

            itemsCustom: [ <?php echo $breakpoints; ?> ],

            responsiveRefreshRate: 50,

        <?php endif; ?>



        <?php if ($speed): ?>

            sdivdeSpeed: <?php echo $speed; ?>,

        <?php endif; ?>



        <?php if ($autoSpeed): ?>

            paginationSpeed: <?php echo $autoSpeed; ?>,

        <?php endif; ?>



        <?php if ($move !== 1): ?>

            scrollPerPage: true,

        <?php endif; ?>



        <?php if ($timeout): ?>

            autoPlay: <?php echo $timeout; ?>,

        <?php endif; ?>



        <?php if ($pause): ?>

            stopOnHover: true,

        <?php endif; ?>



        <?php if ($loop): ?>

            rewindNav: true,

            rewindSpeed: 600,

        <?php else: ?>

            rewindNav: false,

        <?php endif; ?>



        <?php if ($pagination): ?>

            pagination: true,

        <?php else: ?>

            pagination: false,

        <?php endif; ?>



            navigation: true,

            navigationText: false



        }); //end: owl



    });

//]]>

</script>