<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php //$posts = $this->getPostCollection();
$posts = Mage::getResourceModel('wordpress/post_collection');
$posts->addFieldToFilter('main_table.post_content',array('neq'=>''));
$posts->addFieldToFilter('main_table.post_type',array('eq'=>'post'));
/* $posts->getSelect()->joinLeft(array('postmeta' => 'wp_postmeta'), 'main_table.id = postmeta.post_id and postmeta.meta_key="_thumbnail_id" and postmeta.meta_value!=""', '');
$posts->getSelect()->joinLeft(array('postimage' => 'wp_posts'), 'postimage.id = postmeta.meta_value and postimage.post_type="attachment" and postimage.post_mime_type="image/png" and postimage.post_mime_type!=""', ''); */
$posts->getSelect()->limit(4);
/* echo $posts->getSelect()->__toString();exit;*/

/* echo $posts->getSize()." test";exit;
 print_r($posts->getData());
exit;  */
$display_no_of_posts=0;
?>
<?php if ($posts->getSize() > 0): ?>
<script type="text/javascript">// <![CDATA[
//&lt;![CDATA[
		jQuery(function ($) {
$('.responsiveGallery-wrapper').responsiveGallery({
	animatDuration: 400,
	$btn_prev: $('.responsiveGallery-btn_prev'),
	$btn_next: $('.responsiveGallery-btn_next')
});
		});
//]]&gt;
// ]]></script>
<div class="">
  <section id="responsiveGallery-container" class="">
   <!--<a class="responsiveGallery-btn responsiveGallery-btn_prev" href="javascript:void(0);"></a> 
   <a class="responsiveGallery-btn responsiveGallery-btn_next" href="javascript:void(0);"></a>-->
    <div class="col-sm-12 col-md-12">
		<?php foreach($posts as $post): ?>
			<?php $featuredImage = $post->getFeaturedImage(); ?>
			
			<?php $featuredImageobj = $post->getImages()->getFirstItem()->getData(); 
			//if(!empty($featuredImageobj)){			$featuredImageobj->getGuid();}
			?>
			<?php if(!empty($featuredImageobj)): 
                  if($display_no_of_posts < 3):
                  	$display_no_of_posts++;
                    $timestamp=strtotime($post->getPostDate());
                    $day = date('j', $timestamp);
                    $month = date('M', $timestamp);
			     ?>

				<div class="col-sm-4 col-md-4 home_latestpost">
					<a href="<?php echo $post->getPermalink() ?>" class="responsivGallery-link"><img class="lazy" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-original="<?php echo $featuredImageobj['guid'] ?>" alt="" width="350px" height="250px"></a>
				</br>
						<div class="col-md-3" style="padding-left:0px">
							 <div class="home_blog_li_div_date">
					            <div class="home_blog_li_div_day"><?php echo $day; ?></div>
					            <div class="home_blog_li_div_month"><?php echo $month; ?></div>
                            </div>
                        </div>	 			
                        <div class="col-md-9">
                        	<a class="title" href="<?php echo $post->getPermalink() ?>"><?php echo $post->getPostTitle() ?></a>
                        </div>	 							
				</div>
			<?php endif;
                  endif;   
			 ?>
		<?php endforeach; ?>
    </div>
  </section>
</div>
<?php endif; ?>
