<?php
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php
	$_helper = $this->helper('catalog/output');
	$_product = $this->getProduct();
	$theme = $this->helper('ultimo');
	$helperThis = $this->helper('ultimo/template_catalog_product_view');
	$helperSnippets = $this->helper('ultimo/rsnippets');
	//CSS classes based on product type
	$productTypeId = $_product->getTypeId();
	$productTypeClasses = '';
	if ($productTypeId === 'grouped') {
		$productTypeClasses .= ' is-type-grouped';
	}
	//
	$shortDescription = $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description');
	//Rich snippets
	$useRichSnippets = ($helperSnippets->isEnabledOnProductPage() && $productTypeId !== 'grouped');
	$priceProperties = '';
	if ($useRichSnippets)
	{
		$priceProperties = $helperSnippets->getPriceProperties($_product); //Has to be called before getOfferItemscope
	}
	//Get grid classes for product page sections
	$grid = $helperThis->getGridClasses();
	//Product collaterals
	//--------------------------------------------------------------
	$section = array();
	$relatedProductsHtml = '';
	$upsellProductsHtml = '';
    if($_product->getTypeId() == 'bundle' && $_product->getIsFixedKit() ){
       $bundle_option_items_arr=array();
       $bundle_options=Mage::getResourceModel('bundle/selection')->getChildrenIds($_product->getId() ,false);
       foreach ($bundle_options as  $bundle_option) {
           foreach ($bundle_option as  $bundle_option_product) {
              $product_obj=Mage::getModel('catalog/product')->load($bundle_option_product);
              $bundle_option_items_arr[]=intval(Mage::getModel('cataloginventory/stock_item')->loadByProduct($product_obj)->getIsInStock());
           }
          
       }
      if(in_array(0,$bundle_option_items_arr)){
         $_product->setData('is_salable',0);      	
       }
    }
	
	//Related products.
	//If related products not assigned to collateral data container.
	if (!$theme->getCfg('product_page/collateral_related'))
	{
		$replaceRelated = $theme->getCfg('product_page/replace_related');
		if ($replaceRelated == 1) //don't replace with static block
		{
			if ($tmpHtml = trim($this->getChildHtml('related_products_wrapper')))
				$relatedProductsHtml = $tmpHtml;
			//$relatedProductsHtml = trim($this->getChildHtml('related_products_wrapper'));
		}
		elseif ($replaceRelated == 2) //if related is empty, replace with static block
		{
			if ($tmpHtml = trim($this->getChildHtml('related_products_wrapper')))
				$relatedProductsHtml = $tmpHtml;		
			else //related empty
				if ($tmpHtml = $this->getChildHtml('block_product_replace_related'))
					$relatedProductsHtml = '<div class="block_product_replace_related">'. $tmpHtml .'</div>';
		}
		elseif ($replaceRelated == 3) //replace with static block
		{
			if ($tmpHtml = $this->getChildHtml('block_product_replace_related'))
				$relatedProductsHtml = '<div class="block_product_replace_related">'. $tmpHtml .'</div>';
		}
	}
	//Up-sell products.
	//If up-sell products not assigned to collateral data container.
	if (!$theme->getCfg('product_page/collateral_upsell'))
	{
		$replaceUpsell = $theme->getCfg('product_page/replace_upsell');
		if ($replaceUpsell == 1) //don't replace with static block
		{
			if ($tmpHtml = trim($this->getChildHtml('upsell_products_wrapper')))
				$upsellProductsHtml = $tmpHtml;
			//$upsellProductsHtml = $this->getChildHtml('upsell_products_wrapper');
		}
		elseif ($replaceUpsell == 2) //if upsell is empty, replace with static block
		{
			if ($tmpHtml = trim($this->getChildHtml('upsell_products_wrapper')))
				$upsellProductsHtml = $tmpHtml;
			else //upsell empty
				if ($tmpHtml = $this->getChildHtml('block_product_replace_upsell'))
					$upsellProductsHtml = '<div class="block_product_replace_upsell">'. $tmpHtml .'</div>';
		}
		elseif ($replaceUpsell == 3) //replace with static block
		{
			if ($tmpHtml = $this->getChildHtml('block_product_replace_upsell'))
				$upsellProductsHtml = '<div class="block_product_replace_upsell">'. $tmpHtml .'</div>';
		}
	}
	//Assign blocks to selected position
	$p = array();
	/*//Related products
	$position = $theme->getCfg('product_page/related_position');
	if (isset($p[$position]))
		$p[$position] = $p[$position] . $relatedProductsHtml;
	else
		$p[$position] = $relatedProductsHtml;
*/
	//Up-sell products
	$position = $theme->getCfg('product_page/upsell_position');
	if (isset($p[$position]))
		$p[$position] = $p[$position] . $upsellProductsHtml;
	else
		$p[$position] = $upsellProductsHtml;
	//Product collateral data (displayed as tabs or stacked blocks)
	$position = $theme->getCfg('product_page/collateral_position');
	if (isset($p[$position]))
		$p[$position] = $p[$position] . $this->getChildHtml('productCollaterals');
	else
		$p[$position] = $this->getChildHtml('productCollaterals');
?>
<script type="text/javascript">
	var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view nested-container" <?php if ($useRichSnippets) echo $helperSnippets->getProductItemscope(); ?>>
    <?php $_storeId = Mage::app()->getStore()->getId(); ?>
    <?php $_isActive = Mage::getStoreConfig('outofstocksubscription/mail/active', $_storeId); ?>
    <?php if(!$_product->isSaleable() && $_isActive): ?>
        <?php $_url = $this->getUrl('outofstocksubscription') ?>
    <?php else: ?>
        <?php $_url = $this->getSubmitUrl($_product); ?>
    <?php endif; ?>
	<form data-subscribeurl="<?php echo $_url; ?>" action="<?php echo $_url; ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
		<?php echo $this->getBlockHtml('formkey'); ?>
		<div class="no-display">
			<input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
			<input type="hidden" name="related_product" id="related-products-field" value="" />
		</div>
	  <div class="">	
				<div class="product-img-column <?php echo $grid['imgCol']; ?>">
					<?php echo $this->getChildHtml('media') ?>
					<?php if($_product->getIconlabel()!=''): ?>
						<span class="sticker-wrapper top-left"><span class="sticker new"><?php echo $_product->getIconlabel(); ?></span></span>
					<?php endif; ?>
					<?php //echo $this->helper('ultimo/labels')->getLabels($_product); //Product labels ?>
					<?php echo $this->getChildHtml('container_product_image_1'); ?>
				</div>
				<div class="product-primary-column fp-product-detail product-shop <?php echo $grid['primCol']; ?>">
						<h3 itemprop="name"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h3>
					<!--<div <?php if ($useRichSnippets) echo $helperSnippets->getOfferItemscope(); ?>>-->
				     <div class="fp-prod-price">
						 <ul class="nav">	
							<?php echo $this->getChildHtml('product_type_data'); ?>
				
							<?php echo $this->getTierPriceHtml(); ?>
							<?php echo $priceProperties; ?>
							<!--</div> -->
							<?php 
				            $product_sku = $_product->getSku(); 
				            $sa_reviews = "<script type='text/javascript'>  var sa_product = '".$product_sku."'; function saLoadScript(src) { var js = window.document.createElement('script'); js.src = src; js.type = 'text/javascript'; document.getElementsByTagName('head')[0].appendChild(js); } saLoadScript('//www.shopperapproved.com/product/10930/'+sa_product+'.js'); </script><div id='product_just_stars' class='reg'></div>";
				            echo $sa_reviews;
				            //echo $this->getReviewsSummaryHtml($_product, false, true); //magento in built reviews ?>
							<?php /*if ($shortDescription): ?>
								<div class="short-description"><div class="std" itemprop="description"><?php echo $shortDescription; ?></div></div>
							<?php endif; */?>
						 
					           <!-- <label class="fp-prod-id" ><?php echo $this->__("Product ID: ");?>
						            <span class="sku-val">
									<?php echo $_product->getSku();?>
						            </span>
						        </label>-->
			              </ul>
			          </div>  <!-- .fp-prod-price -->  
			       <?php  
			       $grouped_simpleitem_min_qty=Mage::registry('grouped_simpleitem_min_qty');
					if(isset($grouped_simpleitem_min_qty) &&  !empty($grouped_simpleitem_min_qty))
					{
					   $grouped_simpleitem_min_qty=Mage::registry('grouped_simpleitem_min_qty');
				    }
				    else
				    {
				    	$grouped_simpleitem_min_qty='null';
				    }   
		     
		         ?>
			      <?php if(!$_product->isSaleable() && $_isActive && !$_product->isGrouped()): ?>   
			      <div class="row" >
				      	<div class="col-sm-6" >
				                   <div class="sku" style="font-family:Lato; font-weight:bold;">               
									Product Id: 	            <span class="sku-val">
									<?php echo $_product->getSku();?>	            </span>
	                             </div>
				       </div>			        
				       <div class="col-sm-4" id="product_detail_stock_lable" style="padding-top:10px"> 	
			               <strong><?php echo $this->__('Out of Stock') ?></strong>
				       </div>     
				   </div>     
			      <?php  endif; ?>  
			       <?php if($_product->isGrouped() && $grouped_simpleitem_min_qty == 0): ?>   
			        <div class="row" >
			           <div class="col-sm-6" >
			                   <!--<label class="fp-prod-id" ><?php echo $this->__("Product ID: ");?>
						            <span class="sku-val">
									<?php echo $_product->getSku();?>
						            </span>
						        </label> -->
						        <div class="sku" style="font-family:Lato; font-weight:bold;">               
									Product Id: 	            <span class="sku-val">
									<?php echo $_product->getSku();?>	            </span>
	                             </div>
			            </div>
			           <div class="col-sm-4" id="product_detail_stock_lable" style="padding-top:10px"> 	
		                 <strong><?php echo $this->__('Out of Stock') ?></strong>
			           </div> 
			        </div>        
			      <?php  endif; ?>   
			     <!--</div>   -->
				<?php if($_product->isSaleable() && !$_product->isGrouped() ): ?>			
						<?php 
						   $stock = Mage::getModel('cataloginventory/stock_item')->loadByProduct($_product);
						   if($stock->getQty()>0) : ?>
						    <div style="fp-prod-qty form-group">		
								<span class=""><?php if($stock->getQty()>0): ?><?php echo $this->__("Quantity in Stock: ");echo intval($stock->getQty()); ?><?php else: ?>&nbsp;<?php endif; ?></span>
								
				            </div>	
				           <?php endif ?> 
				<?php endif; ?>
				<?php if($_product->isGrouped()): ?>
			
					<div style="display:inline-block">
					<span class="instock-qty">
						<?php if( $grouped_simpleitem_min_qty > 0): ?>
						<?php echo $this->__("Quantity in Stock: ");
						 echo $grouped_simpleitem_min_qty; ?>
						  <input type='hidden' name="group_max_quantity" value="<?php  echo $grouped_simpleitem_min_qty; ?>">
						<?php endif; ?>
					   </span>
						
		            </div>
				<?php endif; ?>
		            <div style="clear:both;margin-top: 15px;"></div>
		            <!--Want more than we have? <a>Click Here</a>-->
					<?php echo $this->getChildHtml('container_product_primary_1'); ?>
					<?php if (isset($p['primCol_1'])) echo $p['primCol_1']; ?>
					<?php if ($sku = $_product->getSku()): ?>
						<?php if ($theme->getCfg('product_page/sku')): ?>
							<div class="sku">
								<span class="label"><?php echo $this->__('SKU'); ?>: </span>
								<span class="value"><?php echo $sku; ?></span>
							</div>
						<?php endif; ?>
						<?php if ($useRichSnippets): ?><meta itemprop="productID" content="sku:<?php echo $sku; ?>" /><?php endif; ?>
					<?php endif; ?>
					<?php echo $this->getChildHtml('alert_urls'); //alerts ?>
					<?php if ($extrahint_html = $this->getChildHtml('extrahint')): //qty increments ?>
						<div class="extrahint-wrapper"><?php echo $extrahint_html; ?></div>
					<?php endif; ?>
					<?php //end: offers ?>
					<?php if (!$this->hasOptions()): //add to cart when no options (e.g. simple products) ?>
						<?php if($_product->isSaleable() && !$_product->isGrouped() ): ?>
							<!-- class="add-to-box">-->
								<?php echo $this->getChildHtml('addtocart') ?>
						 <!--	</div> -->
						<?php endif; ?>
						<?php if($_product->isGrouped() && $grouped_simpleitem_min_qty > 0 ): ?>
							<div class="add-to-box">
								<?php echo $this->getChildHtml('addtocart') ?>
							</div>
						<?php endif; ?>
						<?php echo $this->getChildHtml('extra_buttons') ?>
					<?php endif; ?>
					<?php if ($_product->isSaleable() && $this->hasOptions()): ?>

						<?php if ($container1_html = $this->getChildChildHtml('container1', '', true, true)): ?>
							<div class="container1-wrapper"><?php echo $container1_html; ?></div>
						<?php endif; ?>
					<?php endif;?>	
				<?php if( !$_product->isSaleable() && $_isActive && !$_product->isGrouped()): ?>
		                <div class="product-options">
		                    <table width="100%">
		                                             
		                        <tr>
		            				<td class="product_detail_email_sunscription" style="padding-bottom: 5px; width: 60px;"><?php echo $this->__('Email') ?></td>
		                            <td class="product_detail_email_sunscription">
		                                <input type="text" id="subscription_email" name="subscription_email" value="" style="width:200px;" class="test input-text required-entry validate-email" />
		                            </td>
		                            <td>
		                                <button onclick="productAddToCartForm.submit();" class="button btn-cart pull-left" type="button"><span><span><?php echo $this->__('Subscribe') ?></span></span></button>
		                            </td>
		                        </tr>
		                        <!--<tr>
		                            <td>&nbsp;</td>
		                            <td style="font-size:10px;">
		                                (<?php echo $this->__("Notify me when this product is back in stock") ?>)
		                            </td>
		                        </tr>-->
		                      <!--  <tr>
		                            <td style="">&nbsp;</td>
		                            <td>
		                                <button onclick="productAddToCartForm.submit();" class="button btn-cart pull-left" type="button"><span><span><?php echo $this->__('Subscribe') ?></span></span></button>
		                            </td>
		                        </tr>-->
		                    </table>
		                </div>
		            <?php endif; ?>	
		            <?php if( $_product->isGrouped()  &&  $grouped_simpleitem_min_qty == 0  ): ?>
		                <div class="product-options">
		                    <table width="100%">
		                                             
		                        <tr>
		            				<td class="product_detail_email_sunscription" style="padding-bottom: 5px; width: 60px;"><?php echo $this->__('Email') ?></td>
		                            <td class="product_detail_email_sunscription">
		                                <input type="text" id="subscription_email" name="subscription_email" value="" style="width:200px;" class="test input-text required-entry validate-email" />
		                            </td>
		                            <td>
		                                <button onclick="productAddToCartForm.submit();" class="button btn-cart pull-left" type="button"><span><span><?php echo $this->__('Subscribe') ?></span></span></button>
		                            </td>
		                        </tr>
		                        <!--<tr>
		                            <td>&nbsp;</td>
		                            <td style="font-size:10px;">
		                                (<?php echo $this->__("Notify me when this product is back in stock") ?>)
		                            </td>
		                        </tr>-->
		                      <!--  <tr>
		                            <td style="">&nbsp;</td>
		                            <td>
		                                <button onclick="productAddToCartForm.submit();" class="button btn-cart pull-left" type="button"><span><span><?php echo $this->__('Subscribe') ?></span></span></button>
		                            </td>
		                        </tr>-->
		                    </table>
		                </div>
		            <?php endif; ?>	
					<?php if ($addtoLinksHtml = $this->getChildHtml('addto')): //compare, wishlist, send to friend ?>
						<div class="action-box clearer">
							<?php echo $addtoLinksHtml; ?>
						</div>
					<?php endif; ?>
					<?php if (isset($p['primCol_2'])) echo $p['primCol_2']; ?>
					<?php echo $this->getChildHtml('other'); ?>
					<?php echo $this->getChildHtml('container_product_primary_2'); ?>
				</div> <!-- end: product-shop -->
			</div> <!-- .row -->	
		<?php if (isset($grid['secCol'])): //(!empty($secondaryColUnits)): ?>
			<div class="product-secondary-column <?php echo $grid['secCol']; ?> custom-sidebar-right">
				<div class="inner">
					<?php echo $this->getChildHtml('container_product_secondary_1'); ?>
					<?php if (isset($p['secCol_1'])) echo $p['secCol_1']; ?>
					<?php if ($tmpHtml = $this->getChildHtml('product_secondary_top_placeholder')): //Brand logo ?>
						<div class="feature-wrapper bottom-border"><?php echo $tmpHtml; ?></div>
					<?php endif; ?>
					<?php if (isset($p['secCol_2'])) echo $p['secCol_2']; ?>
					<?php echo $this->getChildHtml('container_product_secondary_2'); ?>
					<?php if (isset($p['secCol_3'])) echo $p['secCol_3']; ?>
				</div>
			</div> <!-- end: product-secondary-column -->
		<?php endif; ?>
		<?php if ($_product->isSaleable() && $this->hasOptions()): ?>
			<?php if ($container2_html = $this->getChildChildHtml('container2', '', true, true)): ?>
				<div class="box-additional<?php echo $grid['cont2Col']; ?>">
					<div class="container2-wrapper"><?php echo $container2_html; ?></div>
				</div>
			<?php endif; ?>
		<?php endif; ?>
	</form>
	<script type="text/javascript">
	//<![CDATA[
		var productAddToCartForm = new VarienForm('product_addtocart_form');
		productAddToCartForm.submit = function(button, url) {
			if (this.validator.validate()) {
				var form = this.form;
				var oldUrl = form.action;
				if (url) {
				   form.action = url;
				}
				var e = null;
				try {
					this.form.submit();
				} catch (e) {
				}
				this.form.action = oldUrl;
				if (e) {
					throw e;
				}
				if (button && button != 'undefined') {
					button.disabled = true;
				}
			}
		}.bind(productAddToCartForm);
		productAddToCartForm.submitLight = function(button, url){
			if(this.validator) {
				var nv = Validation.methods;
				delete Validation.methods['required-entry'];
				delete Validation.methods['validate-one-required'];
				delete Validation.methods['validate-one-required-by-name'];
				if (this.validator.validate()) {
					if (url) {
						this.form.action = url;
					}
					this.form.submit();
				}
				Object.extend(Validation.methods, nv);
			}
		}.bind(productAddToCartForm);
	//]]>
	</script>
	<?php //Lower primary column ?>
	<div class="box-additional <?php echo $grid['lowerPrimCol']; ?>">
		<?php if (isset($p['lowerPrimCol_1'])) echo $p['lowerPrimCol_1']; ?>
		<?php echo $this->getChildHtml('product_additional_data') ?>
        <?php echo $this->getChildHtml('itoris_qa') ?>
		<?php echo $this->getChildHtml('reviews'); //Reviews ?>
	</div> <!-- end: box-tabs -->
<?php /*
if (isset($p[$position]))
	echo $p[$position] = $p[$position] . $relatedProductsHtml;
else
	echo $p[$position] = $relatedProductsHtml;*/
?>
	<?php //Lower secondary column ?>
	<?php if (isset($p['lowerSecCol_2'])): ?>
		<div class="box-additional box-sidebar custom-sidebar-right <?php echo $grid['lowerSecCol']; ?>">
			<div class="inner"><?php echo $p['lowerSecCol_2']; ?></div>
		</div>
	<?php endif; ?>
	<?php if (isset($p['lowerPrimCol_2'])): ?>
		<div class="box-additional <?php echo $grid['lowerPrimCol']; ?>"><?php echo $p['lowerPrimCol_2']; ?></div>
	<?php endif; ?>
<!--<div class="box-additional grid12-12">  -->
<div class="col-md-12 mb15">
<?php
//Related products
	$position = $theme->getCfg('product_page/related_position');
	if (isset($p[$position]))
		echo $p[$position] = $p[$position] . $relatedProductsHtml;
	else
		echo $p[$position] = $relatedProductsHtml;
?>
</div>
<div class="box-additional grid12-12">
<?php echo $this->getLayout()->createBlock('mageworx_alsobought/list')->setTemplate('catalog/product/list/also_bought_multi.phtml')->tohtml(); ?>
</div>
</div> <!-- end: product-view -->
