  <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
			        <div class="blue-curve-box home-page-widget">
			          <div class="row">
			            <div class="col-xs-7 col-sm-7 col-md-7 col-lg-7">
			              <div class="white-text1 pad-top10">Single Colors</div>
			              <div class="widget_select_div"> <span class="widget">
			                <select onchange="gotocategoryurl(this.value, 'Single Colors','FP Brand Option Widget');" autocomplete="off">
			                  <option value="" class="dis-none"></option>
			                  <option value="New Products=http://www.facepaint.com/new-products/single-color-cakes.html">New Products</option>
			                  <option value="For Beginners=http://www.facepaint.com/face-painting-for-beginners/basic-face-paints-700-1-c.html">For Beginners</option>
			                  <option value="Ben Nye=http://www.facepaint.com/vendors/ben-nye/ben-nye-face-paint-263-1-c.html">Ben Nye</option>
			                  <option value="Cameleon=http://www.facepaint.com/face-paints/cameleon-face-paints.html">Cameleon</option>
			                  <option value="Diamond FX=http://www.facepaint.com/vendors/diamond-fx/diamond-fx-face-paints.html">Diamond FX</option>
			                  <option value="Global Colours=http://www.facepaint.com/vendors/global-body-art/face-paints.html">Global Colours</option>
			                  <option value="Graftobian=http://www.facepaint.com/face-paints/graftobian-face-paints.html">Graftobian</option>
			                  <option value="Kryolan=http://www.facepaint.com/vendors/kryolan/kryolan-face-paint-272-1-c.html">Kryolan</option>
			                  <option value="Kryvaline=http://www.facepaint.com/vendors/kryvaline/face-paints.html">Kryvaline</option>
			                  <option value="Mehron Starblend=http://www.facepaint.com/vendors/mehron/mehron-face-paints/mehron-starblend-face-paint-494-1-c.html">Mehron Starblend</option>
			                  <option value="Paradise=http://www.facepaint.com/vendors/paradise/paradise-face-paints-277-1-c.html">Paradise</option>
			                  <option value="Ruby Red=http://www.facepaint.com/vendors/ruby-red/face-paints.html">Ruby Red</option>
			                  <option value="Snazaroo=http://www.facepaint.com/vendors/snazaroo/snazaroo-face-paints-285-1-c.html">Snazaroo</option>
			                  <option value="Tag=http://www.facepaint.com/vendors/tag-body-art/single-colors-32-gm-713-1-c.html">Tag</option>
			                  <option value="Wolfe=http://www.facepaint.com/vendors/wolfe-brothers/wolfe-face-paints-291-1-c.html">Wolfe</option>
			                  <option value="Liquid Face Paint=http://www.facepaint.com/type/face-paints-by-size/liquid-face-paint-704-1-c.html">Liquid Face Paint</option>
			                </select>
			                </span> </div>
			            </div>
			            <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5"> <img src="<?php echo $this->getSkinUrl('images/singlecolor-widget-img.png'); ?>" alt=""> </div>
			          </div>
			        </div>
			        <div class="blue-curve-box home-page-widget">
			          <div class="row">
			            <div class="col-xs-7 col-sm-7 col-md-7 col-lg-7">
			              <div class="white-text1 pad-top10">Palettes</div>
			              <div class="widget_select_div"> <span class="widget">
			                <select onchange="gotocategoryurl(this.value, 'Single Colors','FP Brand Option Widget');" autocomplete="off">
			                  <option value="" class="dis-none"></option>
			                  <option value="New Products=http://www.facepaint.com/new-products/single-color-cakes.html">New Products</option>
			                  <option value="For Beginners=http://www.facepaint.com/face-painting-for-beginners/basic-face-paints-700-1-c.html">For Beginners</option>
			                  <option value="Ben Nye=http://www.facepaint.com/vendors/ben-nye/ben-nye-face-paint-263-1-c.html">Ben Nye</option>
			                  <option value="Cameleon=http://www.facepaint.com/face-paints/cameleon-face-paints.html">Cameleon</option>
			                  <option value="Diamond FX=http://www.facepaint.com/vendors/diamond-fx/diamond-fx-face-paints.html">Diamond FX</option>
			                  <option value="Global Colours=http://www.facepaint.com/vendors/global-body-art/face-paints.html">Global Colours</option>
			                  <option value="Graftobian=http://www.facepaint.com/face-paints/graftobian-face-paints.html">Graftobian</option>
			                  <option value="Kryolan=http://www.facepaint.com/vendors/kryolan/kryolan-face-paint-272-1-c.html">Kryolan</option>
			                  <option value="Kryvaline=http://www.facepaint.com/vendors/kryvaline/face-paints.html">Kryvaline</option>
			                  <option value="Mehron Starblend=http://www.facepaint.com/vendors/mehron/mehron-face-paints/mehron-starblend-face-paint-494-1-c.html">Mehron Starblend</option>
			                  <option value="Paradise=http://www.facepaint.com/vendors/paradise/paradise-face-paints-277-1-c.html">Paradise</option>
			                  <option value="Ruby Red=http://www.facepaint.com/vendors/ruby-red/face-paints.html">Ruby Red</option>
			                  <option value="Snazaroo=http://www.facepaint.com/vendors/snazaroo/snazaroo-face-paints-285-1-c.html">Snazaroo</option>
			                  <option value="Tag=http://www.facepaint.com/vendors/tag-body-art/single-colors-32-gm-713-1-c.html">Tag</option>
			                  <option value="Wolfe=http://www.facepaint.com/vendors/wolfe-brothers/wolfe-face-paints-291-1-c.html">Wolfe</option>
			                  <option value="Liquid Face Paint=http://www.facepaint.com/type/face-paints-by-size/liquid-face-paint-704-1-c.html">Liquid Face Paint</option>
			                </select>
			                </span> </div>
			            </div>
			            <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5"> <img src="<?php echo $this->getSkinUrl('images/pallete-widget-img.png'); ?>" alt=""> </div>
			          </div>
			        </div>
			        <div class="blue-curve-box home-page-widget">
			          <div class="row">
			            <div class="col-xs-7 col-sm-7 col-md-7 col-lg-7">
			              <div class="white-text1  pad-top10">Split Cakes</div>
			              <div class="widget_select_div"> <span class="widget">
			                <select onchange="gotocategoryurl(this.value, 'Single Colors','FP Brand Option Widget');" autocomplete="off">
			                  <option value="" class="dis-none"></option>
			                  <option value="New Products=http://www.facepaint.com/new-products/single-color-cakes.html">New Products</option>
			                  <option value="For Beginners=http://www.facepaint.com/face-painting-for-beginners/basic-face-paints-700-1-c.html">For Beginners</option>
			                  <option value="Ben Nye=http://www.facepaint.com/vendors/ben-nye/ben-nye-face-paint-263-1-c.html">Ben Nye</option>
			                  <option value="Cameleon=http://www.facepaint.com/face-paints/cameleon-face-paints.html">Cameleon</option>
			                  <option value="Diamond FX=http://www.facepaint.com/vendors/diamond-fx/diamond-fx-face-paints.html">Diamond FX</option>
			                  <option value="Global Colours=http://www.facepaint.com/vendors/global-body-art/face-paints.html">Global Colours</option>
			                  <option value="Graftobian=http://www.facepaint.com/face-paints/graftobian-face-paints.html">Graftobian</option>
			                  <option value="Kryolan=http://www.facepaint.com/vendors/kryolan/kryolan-face-paint-272-1-c.html">Kryolan</option>
			                  <option value="Kryvaline=http://www.facepaint.com/vendors/kryvaline/face-paints.html">Kryvaline</option>
			                  <option value="Mehron Starblend=http://www.facepaint.com/vendors/mehron/mehron-face-paints/mehron-starblend-face-paint-494-1-c.html">Mehron Starblend</option>
			                  <option value="Paradise=http://www.facepaint.com/vendors/paradise/paradise-face-paints-277-1-c.html">Paradise</option>
			                  <option value="Ruby Red=http://www.facepaint.com/vendors/ruby-red/face-paints.html">Ruby Red</option>
			                  <option value="Snazaroo=http://www.facepaint.com/vendors/snazaroo/snazaroo-face-paints-285-1-c.html">Snazaroo</option>
			                  <option value="Tag=http://www.facepaint.com/vendors/tag-body-art/single-colors-32-gm-713-1-c.html">Tag</option>
			                  <option value="Wolfe=http://www.facepaint.com/vendors/wolfe-brothers/wolfe-face-paints-291-1-c.html">Wolfe</option>
			                  <option value="Liquid Face Paint=http://www.facepaint.com/type/face-paints-by-size/liquid-face-paint-704-1-c.html">Liquid Face Paint</option>
			                </select>
			                </span> </div>
			            </div>
			            <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5"> <img src="<?php echo $this->getSkinUrl('images/splitcakes-widget-img.png'); ?>" alt=""> </div>
			          </div>
			        </div>
		      </div>