<?php
if (!$this->getMaxPointsNumberToSpent()) return;
?>
<form id="reward-points-form" action="<?php echo $this->getUrl('rewards/checkout/applyPointsPost') ?>" method="post">
    <div class="discount">
        <h2><?php echo $this->__('Use Reward Points') ?></h2>
        <div class="discount-form">
            <label for="points_amount"><?php echo $this->__('You have <b>%s</b> available.', Mage::helper('rewards')->formatPoints($this->getBalancePoints())) ?><br>


            <?php echo $this->__('Enter amount of points to spend:'); ?>
            </label>
            <input type="hidden" name="remove-points" id="remove-points" value="0" />
            <div class="input-box">
                <input class="input-text" id="points_amount" name="points_amount" value="<?php echo $this->getPointsAmount()? $this->htmlEscape($this->getPointsAmount()): '' ?>" />
            </div>
            <div class="input-box">
                <input type='checkbox' id="points_all" name="points_all"
                <?php echo $this->getPointsAmount() == $this->getMaxPointsNumberToSpent()?'checked':''?> />
                <label for="points_all"><?php echo $this->__("Use maximum %s", Mage::helper('rewards')->formatPoints($this->getMaxPointsNumberToSpent()))?></label>
            </div>
            <div class="buttons-set">
                <button type="button" title="<?php echo $this->__('Apply Points') ?>" class="button" onclick="rewardsForm.submit(false)" value="<?php echo $this->__('Apply Points') ?>"><span><span><?php echo $this->__('Apply Points') ?></span></span></button>
                <?php if($this->getPointsAmount()): ?>
                    &nbsp; <button type="button" title="<?php echo $this->__('Cancel Points') ?>" class="button" onclick="rewardsForm.submit(true)" value="<?php echo $this->__('Cancel Points') ?>"><span><span><?php echo $this->__('Cancel Points') ?></span></span></button>
                <?php endif;?>
            </div>
        </div>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
var rewardsForm = new VarienForm('reward-points-form');
rewardsForm.submit = function (isRemove) {
    if (isRemove) {
        $('points_amount').removeClassName('required-entry');
        $('remove-points').value = "1";
    } else {
        $('points_amount').addClassName('required-entry');
        $('remove-points').value = "0";
    }
    return VarienForm.prototype.submit.bind(rewardsForm)();
}

Event.observe($('points_all'), 'click', function(){
    if ($('points_amount').value == <?php echo $this->getMaxPointsNumberToSpent() ?>) {
        $('points_amount').value = '';
    } else {
        $('points_amount').value = <?php echo $this->getMaxPointsNumberToSpent() ?>;
    }
});
Event.observe($('points_amount'), 'keyup', function(){
    var val = parseInt($('points_amount').value);
    if (isNaN(val) || val < <?php echo $this->getMaxPointsNumberToSpent() ?>) {
        $('points_all').checked = false;
    } else {
        $('points_all').checked = true;
        $('points_amount').value = <?php echo $this->getMaxPointsNumberToSpent() ?>;
    }
});
//]]>
</script>