<?php

/* @var $this Mage_Catalog_Block_Product_Compare_Sidebar */



/* TODO:HEAD */

?>
<?php

    $theme = $this->helper('ultimo');

    $_helper = $this->helper('catalog/product_compare');

    $count = $_helper->getItemCount();

    $_items = $count > 0 ? $_helper->getItemCollection() : null;



    if ($count > 0) {

        $mainTitle = $this->__('Compare Products');

        Mage::register('miniCompareProductCount', $count);

    }

    else {

        $mainTitle = $this->__('You have no items to compare.');

    }



    $showLabel = $theme->getCfg('header/compare_label');
	
	$code_store = Mage::app()->getStore()->getCode();

?>

<div id="mini-compare-wrapper-regular">
  <div id="mini-compare" class="mini-compare dropdown<?php echo (!$count ? ' is-empty' : ' is-not-empty'); ?>">
    <div class="mini-compare-heading dropdown-heading cover skip-link skip-compare" title="<?php echo $mainTitle; ?>"> <span><span class="icon ic"><img height="19" width="19" src="<?php if($code_store == 'stripedsocks'):?><?php echo $this->getSkinUrl('images/infortis/_shared/compare.jpg');?><?php else:?><?php echo $this->getSkinUrl('images/flagsrus-compare.jpg');?><?php endif;?>" alt="Compare" /></span>
      <?php if ($count > 0): ?>
      <span class="count"><?php echo $count; ?></span>
      <?php endif; ?>
      <span class="label<?php if (!$showLabel) echo ' no-display'; ?>"><?php echo $this->__('Compare'); ?></span> <span class="caret">&nbsp;</span> </span> </div>
    <div id="header-compare" class="mini-compare-content dropdown-content left-hand block skip-content skip-content--style">
	  <div class="block block-list block-compare">
    <div id="itemcount" style="display: none;"><?php echo $this->__('%d', $_helper->getItemCount()) ?></div>
<!--    <div class="block-title">-->
<!--        <strong><span>--><?php //echo $this->__('Compare Products') ?>
<!--            --><?php //if($_helper->getItemCount() > 0): ?><!-- -->
<!--                <small>--><?php //echo $this->__('(%d)', $_helper->getItemCount()) ?><!--</small>-->
<!--            --><?php //endif; ?>
<!--        </span></strong>-->
<!--    </div>-->
    <div class="block-content">
    <?php if($_helper->getItemCount() > 0): ?>
	      <div class="block-subtitle"><?php echo $this->__('Recently added item(s)'); ?></div>
        <ol id="compare-items">
        <?php foreach($_items as $_index => $_item): ?>
            <li class="item">
                <input type="hidden" class="compare-item-id" value="<?php echo $_item->getId() ?>" />
                <a href="<?php echo $_helper->getRemoveUrl($_item) ?>" title="<?php echo $this->__('Remove This Item') ?>" class="btn-remove" onclick="return confirm('<?php echo $this->__('Are you sure you would like to remove this item from the compare products?') ?>');"><?php echo $this->__('Remove This Item') ?></a>
                <p class="product-name"><a href="<?php echo $this->getProductUrl($_item) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_item, $_item->getName(), 'name') ?></a></p>
            </li>
        <?php endforeach; ?>
        </ol>
        <script type="text/javascript">decorateList('compare-items')</script>
        <div class="actions">
            <a href="<?php echo $_helper->getClearListUrl() ?>" onclick="return confirm('<?php echo $this->__('Are you sure you would like to remove all products from your comparison?') ?>');"><?php echo $this->__('Clear All') ?></a>
            <!--button type="button" title="<?php echo $this->__('Compare') ?>" class="button" onclick="popWin('<?php echo $_helper->getListUrl() ?>','compare','top:0,left:0,width=820,height=600,resizable=yes,scrollbars=yes')"><span><span><?php echo $this->__('Compare') ?></span></span></button-->
		   <button type="button" title="<?php echo $this->__('Compare Products') ?>" class="button btn-inline" onclick="window.open('<?php echo $_helper->getListUrl() ?>','_self')"><span><span><?php echo $this->__('Compare') ?></span></span></button>
        </div>
    <?php else: ?>
        <p class="empty"><?php echo $this->__('You have no items to compare.') ?></p>
    <?php endif; ?>
    </div>
</div>
    </div>
    <!-- end: dropdown-content --> 
    
  </div>
  <!-- end: mini-compare --> 
  
</div>
<!-- end: mini-compare-wrapper-regular --> 

