<!-- by brt-->
<?php
$attribute = Mage::getSingleton('eav/config')->getAttribute('catalog_product', 'fl_filter_section');
$options = $attribute->getSource()->getAllOptions(false);
$sel_filter = Mage::app()->getRequest()->getParam('searchBarOrder');
?>
<!--by brt ends-->
<form id="search_mini_form" action="<?php echo $this->helper('solrsearch')->getResultUrl() ?>" method="get" class="topsearch">
    <!-- by brt-->
    <div class="searchBarnav"> <!-- Style sheet added on 08032016 -->
        <select id="resizing_select" name="searchBarOrder" style="border:none;height: 43px;margin-left: 3px;">  <!-- Style sheet added on 08032016 -->
            <option value="">All</option>

            <?php    foreach($options as $key => $filtertype){ ?>
                <option value="<?php echo $filtertype['label'];?>" <?php if($sel_filter == $filtertype['label']): ?>selected="selected"<?php endif; ?>><?php echo $filtertype['label'];?></option>
           <?php }  ?>

        </select>
		<select id="width_tmp_select" style="display:none;">
		  <option id="width_tmp_option"></option>
		</select>
    </div>
    <!--by brt ends-->
    <div class="form-search">
        <label for="search"><?php echo $this->__('Search') ?>:</label>

        <input id="search" style="border:none" type="text" name="<?php echo $this->helper('catalogsearch')->getQueryParamName() ?>" value="<?php echo trim(trim($this->helper('catalogsearch')->getEscapedQueryText(),'"')) ?>" class="input-text" />
        <button type="submit" title="<?php echo $this->__('Search') ?>" class="button"><span><span><?php echo $this->__('Search') ?></span></span></button>
        <div id="search_autocomplete" class="search-autocomplete"></div>
        <script type="text/javascript">
        //<![CDATA[
            var searchForm = new Varien.searchForm('search_mini_form', 'search', '<?php echo $this->__('') ?>');
            var SolrBridgeAutocomplete = new SolrBridgeSearch('search',<?php echo $this->helper('solrsearch')->getAutocompleteConfig('search', 'search_mini_form')?>);
        //]]>
        </script>
    </div>
</form>
<script type="text/javascript">
	jQuery(document).ready(function() {
	  jQuery('#resizing_select').change(function(){
		jQuery("#width_tmp_option").html(jQuery('#resizing_select option:selected').text()); 
		jQuery(this).width(jQuery("#width_tmp_select").width());  
	  });
	});
</script>