
        <div class="review-box">
          <div class="review-title">
            <h3>Reviews </h3>
          </div>
          <div class="review-post">
            <div class="review-star"><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i></div>
            <div class="review-label">Anonimus</div>
            <div class="review-date">24 Oct 2015</div>
            <div class="review-subtitle">Easy website navigation</div>
          </div>
          <div class="review-post">
            <div class="review-star"><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i></div>
            <div class="review-label">Anonimus</div>
            <div class="review-date">24 Oct 2015</div>
            <div class="review-subtitle">Easy website navigation</div>
          </div>
          <div class="review-post">
            <div class="review-star"><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i></div>
            <div class="review-label">Anonimus</div>
            <div class="review-date">24 Oct 2015</div>
            <div class="review-subtitle">Easy website navigation</div>
          </div>
          <div class="review-post">
            <div class="review-star"><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i></div>
            <div class="review-label">Anonimus</div>
            <div class="review-date">24 Oct 2015</div>
            <div class="review-subtitle">Easy website navigation</div>
          </div>
        </div>