
        <div class="side-title">
          <h3>Color</h3>
        </div>
        <div class="color1">
          <div class="input-style3">
            <div class="input-style2">
              <input type="radio" name="color_id[]" onclick="submit_frm('FPfilter')" value="39" autocomplete="off">
              Regular </div>
            <div class="input-style2">
              <input type="radio" name="color_id[]" onclick="submit_frm('FPfilter')" value="38" autocomplete="off">
              Metallic </div>
            <div style="float: left;font-size: 12px;">
              <input type="radio" name="color_id[]" onclick="submit_frm('FPfilter')" value="35" autocomplete="off">
              Neon </div>
          </div>
          <div style="float:left;width:52px;">
            <div class="filterColorStyle" style=" background:#FFFFFF; ">
              <input type="checkbox" class="filterColorCheckbox side-label" id="FPcolorCheckbox28" name="color_id[]" onclick="submit_frm('FPfilter')" value="28" autocomplete="off">
              <label class="filterColorCheckbox-lable" name="FPcolorCheckbox28" onclick="check(this, 'FPfilter')" title="White, Off White"></label>
            </div>
            <div class="filterColorStyle" style=" background:#999999; ">
              <input type="checkbox" class="filterColorCheckbox side-label" id="FPcolorCheckbox12" name="color_id[]" onclick="submit_frm('FPfilter')" value="12" autocomplete="off">
              <label class="filterColorCheckbox-lable" name="FPcolorCheckbox12" onclick="check(this, 'FPfilter')" title="Silver, Grey"></label>
            </div>
            <div class="filterColorStyle" style=" background:#FF0000; ">
              <input type="checkbox" class="filterColorCheckbox side-label" id="FPcolorCheckbox24" name="color_id[]" onclick="submit_frm('FPfilter')" value="24" autocomplete="off">
              <label class="filterColorCheckbox-lable" name="FPcolorCheckbox24" onclick="check(this, 'FPfilter')" title="Red, Dark Red"></label>
            </div>
            <div class="filterColorStyle" style=" background:#000000; ">
              <input type="checkbox" class="filterColorCheckbox side-label" id="FPcolorCheckbox1" name="color_id[]" onclick="submit_frm('FPfilter')" value="1" autocomplete="off">
              <label class="filterColorCheckbox-lable" name="FPcolorCheckbox1" onclick="check(this, 'FPfilter')" title="Black"></label>
            </div>
          </div>
          <div style="float:left;width:52px;">
            <div class="filterColorStyle" style=" background:#FFCC99; ">
              <input type="checkbox" class="filterColorCheckbox side-label" id="FPcolorCheckbox7" name="color_id[]" onclick="submit_frm('FPfilter')" value="7" autocomplete="off">
              <label class="filterColorCheckbox-lable" name="FPcolorCheckbox7" onclick="check(this, 'FPfilter')" title="Bronze, Copper, Peach, Beige"></label>
            </div>
            <div class="filterColorStyle" style=" background:#FF6600; ">
              <input type="checkbox" class="filterColorCheckbox side-label" id="FPcolorCheckbox14" name="color_id[]" onclick="submit_frm('FPfilter')" value="14" autocomplete="off">
              <label class="filterColorCheckbox-lable" name="FPcolorCheckbox14" onclick="check(this, 'FPfilter')" title="Orange, Neon Orange"></label>
            </div>
            <div class="filterColorStyle" style=" background:#663300; ">
              <input type="checkbox" class="filterColorCheckbox side-label" id="FPcolorCheckbox6" name="color_id[]" onclick="submit_frm('FPfilter')" value="6" autocomplete="off">
              <label class="filterColorCheckbox-lable" name="FPcolorCheckbox6" onclick="check(this, 'FPfilter')" title="Dark Orange, Brown"></label>
            </div>
            <div class="filterColorStyle" style=" background:#FF19B2; ">
              <input type="checkbox" class="filterColorCheckbox side-label" id="FPcolorCheckbox18" name="color_id[]" onclick="submit_frm('FPfilter')" value="18" autocomplete="off">
              <label class="filterColorCheckbox-lable" name="FPcolorCheckbox18" onclick="check(this, 'FPfilter')" title="Light Pink, Dark Pink, Pink"></label>
            </div>
          </div>
          <div style="float:left;width:52px;">
            <div class="filterColorStyle" style=" background:#CC3399; ">
              <input type="checkbox" class="filterColorCheckbox side-label" id="FPcolorCheckbox20" name="color_id[]" onclick="submit_frm('FPfilter')" value="20" autocomplete="off">
              <label class="filterColorCheckbox-lable" name="FPcolorCheckbox20" onclick="check(this, 'FPfilter')" title="Fuchsia"></label>
            </div>
            <div class="filterColorStyle" style=" background:#660099; ">
              <input type="checkbox" class="filterColorCheckbox side-label" id="FPcolorCheckbox21" name="color_id[]" onclick="submit_frm('FPfilter')" value="21" autocomplete="off">
              <label class="filterColorCheckbox-lable" name="FPcolorCheckbox21" onclick="check(this, 'FPfilter')" title="Lavender, Purple"></label>
            </div>
            <div class="filterColorStyle" style=" background:#99CCFF; ">
              <input type="checkbox" class="filterColorCheckbox side-label" id="FPcolorCheckbox4" name="color_id[]" onclick="submit_frm('FPfilter')" value="4" autocomplete="off">
              <label class="filterColorCheckbox-lable" name="FPcolorCheckbox4" onclick="check(this, 'FPfilter')" title="Turquoise, Light Blue"></label>
            </div>
            <div class="filterColorStyle" style=" background:#0000FF; ">
              <input type="checkbox" class="filterColorCheckbox side-label" id="FPcolorCheckbox2" name="color_id[]" onclick="submit_frm('FPfilter')" value="2" autocomplete="off">
              <label class="filterColorCheckbox-lable" name="FPcolorCheckbox2" onclick="check(this, 'FPfilter')" title="Blue, Dark Blue"></label>
            </div>
          </div>
          <div style="float:left;width:52px;">
            <div class="filterColorStyle" style=" background:#FCEB77; ">
              <input type="checkbox" class="filterColorCheckbox side-label" id="FPcolorCheckbox30" name="color_id[]" onclick="submit_frm('FPfilter')" value="30" autocomplete="off">
              <label class="filterColorCheckbox-lable" name="FPcolorCheckbox30" onclick="check(this, 'FPfilter')" title="Light Yellow, Dark Yellow, Yellow"></label>
            </div>
            <div class="filterColorStyle" style=" background:#FFCC00; ">
              <input type="checkbox" class="filterColorCheckbox side-label" id="FPcolorCheckbox32" name="color_id[]" onclick="submit_frm('FPfilter')" value="32" autocomplete="off">
              <label class="filterColorCheckbox-lable" name="FPcolorCheckbox32" onclick="check(this, 'FPfilter')" title="Gold"></label>
            </div>
            <div class="filterColorStyle" style=" background:#18D81E; ">
              <input type="checkbox" class="filterColorCheckbox side-label" id="FPcolorCheckbox10" name="color_id[]" onclick="submit_frm('FPfilter')" value="10" autocomplete="off">
              <label class="filterColorCheckbox-lable" name="FPcolorCheckbox10" onclick="check(this, 'FPfilter')" title="Lime &amp; Light Green"></label>
            </div>
            <div class="filterColorStyle" style=" background:#008518; ">
              <input type="checkbox" class="filterColorCheckbox side-label" id="FPcolorCheckbox9" name="color_id[]" onclick="submit_frm('FPfilter')" value="9" autocomplete="off">
              <label class="filterColorCheckbox-lable" name="FPcolorCheckbox9" onclick="check(this, 'FPfilter')" title="Green, Dark Green"></label>
            </div>
          </div>
        </div>
       
  <div style="clear:both;"></div>