<?php
/* called in cms {{block type="core/template" template="page/html/wordpress-homepage-feed.phtml"}}*/
?>
  
<?php
    $channel = new Zend_Feed_Rss('http://www.mysitename.co.uk/news/feed/');
 ?>
  
<div id="wp-feed" class="RoleBlock">
     <h2><a href="/news/" title="My site news"><?php echo $channel->title(); ?> News &amp; Events</a></h2>
      
     <?php foreach ($channel as $key=>$item) {  ?>
       
        <div class="post-block">
            <h3><a href="<?php echo $item->link(); ?>"><?php echo $item->title(); ?></a></h3>
            <p><?php echo $item->description(); ?></p>        
        </div>  
     <?php } ?>
         
</div>