<?php

/**

 * Featured Products Slider

 */
Varien_Profiler::start('LabelForCodeFragmentToProfile');
?>

<?php

    $bestseller_collection = $this->getBestsellerProduct();//$this->getLoadedProductCollection();
/* 	$bestseller_collection->joinField('is_in_stock',
'cataloginventory/stock_item',
'is_in_stock',
'product_id=entity_id',
'is_in_stock=1',
'{{table}}.stock_id=1',
'left'); */
   /*  foreach($bestseller_collection as $collection){

        $pr_result = $collection->getEntityId();
        $_product = $this->getProducts($pr_result); 
        $pro[] = $_product;
    }
    if($this->getChooseProducts() == "1") {

        $result = $pro;

    }elseif($this->getChooseProducts() == "2") {

       $result = $this->getProductIds();

    }else{

        if($this->getSortOrder() == 1){

            $result = array_unique(array_merge($pro, $this->getProductIds()));

        }elseif($this->getSortOrder() == 2){

            $result = array_unique(array_merge($this->getProductIds(),$pro));

        }else{

            $result = array_unique(array_merge($pro, $this->getProductIds()));

            shuffle($result);

        }

    }
    $_productCollection = $result;    */
	//echo "<pre>";print_r($_productCollection);
?>

<?php if ($bestseller_collection): ?>

<?php

    $_helper = $this->helper('catalog/output');

    $theme = $this->helper('ultimo');

    $helpLabels = $this->helper('ultimo/labels');

    $helpTemplate = $this->helper('ultimo/template');

    $helpImg = $this->helper('infortis/image');

    $sliderClasses = '';

    $gridClasses = '';



    $hash = $this->getFrontendHash();

    $sliderId = "itemslider-bestseller-{$hash}";



    //Slider parameters

    //--------------------------------------------------------------



    //Responsive mode on/off

    $isResponsive = $this->getIsResponsive(); //param: is_responsive

    if ($isResponsive === NULL) //Param not set

    {

        $isResponsive = true; //IMPORTANT: enabled by default

    }



    //Assign number of items in a row to specific viewport width

    $breakpoints = $this->getBreakpoints(); //param: breakpoints

    if ($breakpoints === NULL) //Param not set

    {

        $breakpoints = '[0, 1], [320, 2], [480, 3], [768, 4], [960, 5], [1280, 6]'; //Set default breakpoints

    }



    //Number of items in a row displayed if responsive mode is off

    $showItems = $this->getShowItems(); //param: show_items

    if (!$showItems) //Param not set or equals zero

    {

        $showItems = 5; //Set default number of items

    }



    //Pagination on/off

    $pagination = $this->getPagination(); //param: pagination



    //Slider initial delay

    $initDelay = 0;

    $initDelay = intval($this->getInitDelay()); //param: init_delay



    //Image width

    $imgWidth = $this->getImgWidth(); //param: img_width

    if ($imgWidth === NULL) //Param not set

    {

        $imgWidth = 196; //Set default value

    }

    else

    {

        $imgWidth = intval($imgWidth);

    }



        //Image aspect ratio

        if ($theme->getCfg('category/aspect_ratio'))

        {

            $imgHeight = 0; //Keep aspect ratio - height will be calculated automatically based on width

        }

        else

        {

            $imgHeight = $imgWidth; //Don't keep aspect ratio - height is the same as width

        }



    //Image height

    if ($this->getImgHeight() !== NULL) //param: img_height

    {

        //If param is set, it overrides default height and aspect ratio settings

        $imgHeight = intval($this->getImgHeight());

    }



    //Slider timeout. Set to enable automatic scrolling.

    $timeout = $this->getTimeout(); //param: timeout

    if ($timeout === NULL) //Param not set

    {

        $timeout = intval($theme->getCfg('product_slider/timeout'));

    }

    else

    {

        $timeout = intval($timeout);

    }



    //Number of items that should move on scrolling

    $move = $this->getMove(); //param: move

    if ($move === NULL) //Param not set

    {

        $move = 0; //By default scroll all visible items

    }

    else

    {

        $move = intval($move);

    }



    //If set, slider will loop

    $loop = $this->getLoop(); //param: loop

    if ($loop === NULL) //Param not set

    {

        $loop = $theme->getCfg('product_slider/loop');

    }



    //Speed (arrows / touch swipe)

    $speed = intval($theme->getCfg('product_slider/speed'));



    //Speed (automatic scrolling / pagination)

    $autoSpeed = intval($theme->getCfg('product_slider/auto_speed'));



    //Pause slider on mouse hover

    $pause = $theme->getCfg('product_slider/pause');



    //Lazy loading

    $lazy = $theme->getCfg('product_slider/lazy');



    //Slider classes

    //--------------------------------------------------------------

    if($isResponsive)

    {

        $sliderClasses .= ' itemslider-responsive';

    }



    if ($_collectionSize == 1)

    {

        $sliderClasses .= ' single-item';

    }



    //Product grid classes

    //--------------------------------------------------------------

    //Size of grid elements

    $size = $this->getSize(); //param: size

    if ($size)

    {

        $gridClasses = ' ' . $size;

    }

    else

    {

        if ($showItems >= 8)

        {

            $gridClasses = ' size-xs';

        }

        elseif ($showItems >= 6)

        {

            $gridClasses = ' size-s';

        }

    }



    //Align elements to the center

    if ($this->getCentered()) //param: centered

    {

        $gridClasses .= ' centered';

    }



    //Set equal height for all items

    if ($this->getEqualHeight()) //param: equal_height

    {

        $gridClasses .= ' equal-height';

    }

?>


<div class="page-title">
<h3 class="section-title">Best Sellers</h3>
</div>

<div class="itemslider-wrapper slider-arrows1 slider-arrows1-pos-top-right slider-pagination1">

    <div id="<?php echo $sliderId; ?>" class="products-grid category-products-grid itemgrid itemgrid-adaptive centered hover-effect equal-height itemslider<?php if($sliderClasses) echo $sliderClasses; ?> products-grid<?php if($gridClasses) echo $gridClasses; ?>">
    <?php //$productcount = count(array_filter($_productCollection)); ?>
	<?php $productcount = $bestseller_collection->getSize();  ?>
    <?php foreach ($bestseller_collection as $_product): 
	if($_product){
	?>
		<?php 
			$productid = $_product->getId();
			$producturl = $_product->getProductUrl();
			$imglabel = $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true); 
			$product_img = $helpImg->getImg ($_product, $imgWidth, $imgHeight, 'small_image'); 
			$iconlabel = $_product->getIconlabel(); 
			$productname = $_product->getName(); 
			$productsku =  $_product->getSku(); ?>
        <div class="item" id="<?php echo $productid;?>">

        

            <div class="product-image-wrapper" style="max-width:<?php echo $imgWidth; ?>px;">

            
                <a href="<?php echo $producturl ?>" title="<?php echo $imglabel; ?>" class="product-image">

                    

                    <?php if ($lazy): ?>

						<?php if($productcount>3): ?>
							<img class="owl-lazy"
								 data-src="<?php echo $product_img; ?>"
								 alt="<?php echo $imglabel; ?>"/>
						<?php else: ?>
							<img class="lazy"
								 data-original="<?php echo $product_img; ?>"
								 src="<?php echo $this->getSkinUrl('images/loader.gif') ?>"
								 alt="<?php echo $imglabel; ?>"/>
						<?php endif; ?>

                    <?php else: ?>

                        <img src="<?php echo $product_img; ?>" alt="<?php echo $imglabel; ?>" />

                    <?php endif; ?>



                    <?php if ($theme->getCfg('category/alt_image')): ?>

                        <?php echo $theme->getAltImgHtml($_product, $imgWidth, $imgHeight); ?>

                    <?php endif; ?>



					<?php //echo $helpLabels->getLabels ($_product); //Product labels ?>
					<?php if($iconlabel!=''): ?>
							<!--span class="sticker-wrapper top-left"><span class="sticker new"><?php echo $iconlabel; ?></span></span-->
							<span class="tag-label-<?php echo strtolower(str_replace(' ', '', $iconlabel)); ?>"></span>
					<?php endif; ?>

                </a>

            

                <?php //Add-to links

                    if ($theme->getCfg('category_grid/display_addtolinks') != 0 

                        && $theme->getCfg('category_grid/addtolinks_simple'))

                    {

                        if ($theme->getCfg('category_grid/display_addtolinks') == 1) //Display on hover

                        {

                            echo $helpTemplate->getCategoryAddtoLinksIcons(

                            $_product, $this->getAddToCompareUrl($_product), 'addto-links-icons addto-onimage visible-onhover');

                        }

                        else //Always display

                        {

                            echo $helpTemplate->getCategoryAddtoLinksIcons(

                            $_product, $this->getAddToCompareUrl($_product), 'addto-links-icons addto-onimage');

                        }

                    }

                ?>

                

            </div> <!-- end: product-image-wrapper -->

            <h3 class="product-name"><a href="<?php echo $producturl ?>" title="<?php echo $this->stripTags($productname, null, true) ?>"><?php echo $productname ?></a></h3>

            <?php /*if($_product->getRatingSummary()): ?>

                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>

            <?php endif;*/ ?>

            <?php echo $this->getPriceHtml($_product, true, $hash) ?>

            <div class="actions">



                <?php if (!$this->getHideButton()): ?>

                    <?php if(!$_product->canConfigure() && $_product->isSaleable()): ?>
			
                 <!--=================== by brt =================-->
                <?php
                $stock = Mage::getSingleton('cataloginventory/stock_item')->loadByProduct($_product);
                $productCount=intval($stock->getQty());
                ?>
                <!--=================== by brt ends =================-->
                  <?php $cartUrl = Mage::helper('checkout/cart')->getAddUrl($_product); ?>
					<form action="<?php echo $cartUrl; ?>" method="post" class="product_addtocart_form product_addtocart_form_<?php echo $productsku; ?>" name="product_addtocart_form<?php echo $productid; ?>" id="product_addtocart_form<?php echo $productid; ?>"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
						<?php echo $this->getBlockHtml('formkey'); ?>
						<input type="hidden" id="<?php echo $productsku."-addtourl"; ?>" name="addtourl" value="<?php echo $cartUrl;?>">
						<input type="hidden" name="product" value="<?php echo $productid;?>">
						<input type="hidden" name="related_product" value="">
						<input type="hidden" name="return_url" value="">
						<div class="<?php echo $productsku."-addto"; ?>">
							<select class="input-text qty" name="qty" id="qty">
							<?php $i = 1 ?>
							<?php do { ?>
								<option value="<?php echo $i?>">
									<?php echo $i ?>
									<?php $i++ ?>
								</option>
							<?php } while ($i <= $productCount) ?>
							</select>
							<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart <?php echo $productsku."-del"; ?>" id="" onclick="ajaxaddtocart.ajaxCartSubmit(productAddToCartForm<?php echo $productid; ?>);"><span><i class="icon ic ic-bag"></i><span><?php echo $this->__('Add to Cart') ?></span></span></button>
						</div>
						<div class="<?php echo $productsku."-addremove"; ?>" style="display:none;">
							<button type="button" title="<?php echo $this->__('Added/Remove') ?>" class="button btn-cart  add-remove" onclick="ajaxaddtocart.ajaxCartSubmit(productAddToCartForm<?php echo $productid; ?>);"><span><span><?php echo $this->__('Added/Remove') ?></span></span></button>
						</div>
					</form>
                    <script type="text/javascript">
                            //<![CDATA[
                            var productAddToCartForm<?php echo $productid; ?> = new VarienForm('product_addtocart_form<?php echo $productid; ?>');
                            //]]>
                    </script>
                    <?php elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>

                        <a title="<?php echo $this->__('See Options') ?>" style="float:none" class="button btn-cart" href="<?php echo $producturl ?>"><?php echo $this->__('See Options') ?></a>

                    <?php else: ?>

                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>

                    <?php endif; ?>

                <?php endif; ?>



                <?php //Add-to links

                if ($theme->getCfg('category_grid/display_addtolinks') != 0 && !$theme->getCfg('category_grid/addtolinks_simple'))

                {

                    if ($theme->getCfg('category_grid/display_addtolinks') == 1) //Display on hover

                        echo $helpTemplate->getCategoryAddtoLinks($_product, $this->getAddToCompareUrl($_product), 'addto-gaps-right addto-texticons display-onhover');

                    else //Always display

                        echo $helpTemplate->getCategoryAddtoLinks($_product, $this->getAddToCompareUrl($_product), 'addto-gaps-right addto-texticons');

                }

                ?>



            </div>
            
            <div class="clearer"></div>    
                <?php //$getId = $productid;?>
               <?php $getIdcls = "rating-and-qty-block".$productid;?>
               <div class="rating-and-qty-block  <?php echo $getIdcls;?>"><!-- start: rating-and-qty-block-->                    
                   <div class="ratings"> <!-- start: ratings -->                 
                    	<div class="star_container <?php echo $productsku;?>"></div>
                   </div><!-- end: ratings -->                    
                       <?php  
                           //$stock = Mage::getModel('cataloginventory/stock_item')->loadByProduct($_product); ?>
						<?php if(!$_product->canConfigure() && $_product->isSaleable()): ?>
							<?php if($productCount>0): ?>
								<div class="qty-in-stock"><!-- start: Qty in stock -->
									<? echo $this->__("Qty in Stock: ").intval($productCount); ?>
							   </div><!-- end: Qty in stock -->                   
							<?php endif; ?>               
						<?php endif; ?>               
                   
               </div><!-- end: rating-and-qty-block-->

            

        </div>

    <?php } endforeach; ?>

    </div> <!-- end: itemslider -->

</div> <!-- end: itemslider-wrapper -->

<script type="text/javascript">

//<![CDATA[

    jQuery(function($) {

        

        var owl = $('#<?php echo $sliderId; ?>');

        owl.owlCarousel({


  
        <?php if ($lazy): ?>

            lazyLoad: true,

        <?php endif; ?>

        <?php if(!$isResponsive): ?>

            responsive: false,

           // items: <?php echo $showItems; ?>,

        <?php else: ?>

            // itemsCustom: [ <?php echo $breakpoints; ?> ],
            responsiveClass:true,
            responsive: {0:{items:1},480:{items:2},960:{items:4}},

            responsiveRefreshRate: 50,

        <?php endif; ?>



        <?php if ($speed): ?>

            slideSpeed: <?php echo $speed; ?>,

        <?php endif; ?>



        <?php if ($autoSpeed): ?>

            paginationSpeed: <?php echo $autoSpeed; ?>,

        <?php endif; ?>



        <?php if ($move !== 1): ?>

            scrollPerPage: true,

        <?php endif; ?>



        <?php if ($timeout): ?>

            autoPlay: <?php echo $timeout; ?>,

        <?php endif; ?>



        <?php if ($pause): ?>

            stopOnHover: true,

        <?php endif; ?>



        <?php if ($loop): ?>

            loop: true,

            rewindSpeed: 600,

        <?php else: ?>

            rewindNav: false,

        <?php endif; ?>



        <?php if ($pagination): ?>

            pagination: true,

        <?php else: ?>

            pagination: false,

        <?php endif; ?>



            nav: true,

            navigationText: false



        }); //end: owl



    });

//]]>

</script>

<?php endif; ?>

<script type="text/javascript">
jQuery(document).ready(function () {
if (jQuery(window).width() > 768)
{		
	jQuery(".rating-and-qty-block").hide();
	jQuery('.products-grid  .item').on('mouseover', function() {
		var pid = jQuery(this).attr('id');
		//alert(pid);
    jQuery('.rating-and-qty-block'+pid).show();
}).on('mouseout', function() {
	var pid = jQuery(this).attr('id');
    jQuery('.rating-and-qty-block'+pid).hide();
});
}else
{
	jQuery(".rating-and-qty-block").show();
}
});
</script>
<?php Varien_Profiler::stop('LabelForCodeFragmentToProfile'); ?>