<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/<?php echo $this->getLocaleCode()?>/sdk.js#xfbml=1&appId=<?php echo $this->getAppId()?>&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<script type="text/javascript">
window.oldFbInit = window.fbAsyncInit || function(){};
window.fbAsyncInit = function() {
window.oldFbInit();
    FB.Event.subscribe('xfbml.render', function(b){
        FB.Event.subscribe('edge.create',function(a) {
            new Ajax.Request('<?php echo $this->getLikeUrl() ?>?url=<?php echo $this->getCurrentEncodedUrl()?>',
            {
                onSuccess: function(response) {
                    $('status-message').update(response.responseText);
                    $('facebook-message').update('');
                }
            });
        });
        FB.Event.subscribe('edge.remove',function(a){
            new Ajax.Request('<?php echo $this->getUnlikeUrl() ?>?url=<?php echo $this->getCurrentEncodedUrl()?>',{
                onSuccess: function(response) {
                    $('status-message').update(response.responseText);
                    $('facebook-message').update('');
                }
            });
        });
    });
};
</script>