<style>
<?php if(Mage::getStoreConfigFlag('giftcards/default/split_amount')):?>
.card-amount {
    border-bottom: solid 1px;
    cursor: pointer;
}
<?php endif; ?>
#edit-div {
    display: none;
}
#apply-btn img {
    vertical-align: middle !important;
    margin-top: 5px;
    margin-left: 3px;
    cursor: pointer;
}
</style>

<?php $oGiftCardSession = Mage::getSingleton('giftcards/session'); ?>
<?php $loadFromSSL = $_SERVER['SERVER_PORT']==443?true:false; ?>
<?php $isGiftCard = $this->isGiftCard(); ?>

<div class="discount">
    <h2><?php echo $this->__('Gift Cards'); ?></h2>

    <div class="discount-form">
    <?php if(!$isGiftCard) : ?>
        <form method="post" action="<?php echo $this->getUrl('giftcards/cart/activateGiftCard', array( '_secure'=>$loadFromSSL)); ?>" id="activateGiftCard">
            <label for="giftcard_code"><?php echo $this->__('Redeem and use your Gift Card now'); ?></label>
            <div class="input-box">
                <input value="" name="giftcard_code" id="giftcard_code" class="input-text">
            </div>
            <div class="buttons-set">
                <button value="<?php echo $this->__('Activate') ?>" onclick="giftCardForm.submit(true)" class="button"
                        title="Activate" type="button"><span><span><?php echo $this->__('Activate') ?></span></span>
                </button>
            </div>
        </form>

        <?php $currencySymbol = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); $temp = 0; ?>
        <?php if($oGiftCardSession->getActive())
                    echo '<br/>';
                    foreach($oGiftCardSession->getFrontOptions() as $k => $v)
                    {
                        if($temp) {
                            echo '<br/><br/>';
                        }
                        echo '<div id="edit-div""><input id="edit-card-amount-'.$k.'" style="width:50px;text-align:right;" value="'. $v['applied']. '" />';
                        echo '<span id="apply-btn"><a onclick="applyAmount('.$k.'); return false;"><img src="'.$this->getSkinUrl('images/giftcard_apply.gif').'" alt=""></a></span>';
                        echo '</div><b><span id="card-amount" class="card-amount" onclick="editAmount()">'.$currencySymbol.$v['applied'].'</span> '.$this->__('applied from Gift Card').' '.$v['code'].'.';
                        echo '<input id="edit-card-code-'.$k.'" style="display:none;" value="'.$v['code'].'">';
                        echo '<br/>';
                        echo $this->__('Remaining card balance').': '.$currencySymbol.$v['remaining'].'. (<a href="'.$this->getUrl("giftcards/cart/deActivateGiftCard/id/$k", array( '_secure'=>$loadFromSSL)).'">'.$this->__('Remove').'</a>)</b>';
                        $temp = 1;
                    }
        ?>
    <?php else : ?>    
        <?php echo $this->__('Gift cards cannot be used to purchase gift cards'); ?>
    <?php endif; ?>
    </div>
    <script type="text/javascript">
        //&lt;![CDATA[
        var deActivateGiftCardForm = new VarienForm('deActivateGiftCard');
        var giftCardForm = new VarienForm('activateGiftCard');
        //]]&gt;
    </script>

</div>

<script type="text/javascript">
    function editAmount(){
      <?php if(Mage::getStoreConfigFlag('giftcards/default/split_amount')):?>
        $('card-amount').hide();
        $('edit-div').setStyle({display : 'inline-flex'});
      <?php endif;?>
      return true;
    }

    function applyAmount(id){
        var code = $('edit-card-code-'+id).value;
        var amount = $('edit-card-amount-'+id).value;
        setLocation("<?php echo $this->getUrl("giftcards/cart/deActivateGiftCard", array( '_secure'=>$loadFromSSL))?>id/"+id);
        setLocation("<?php echo $this->getUrl('giftcards/cart/activateGiftCard', array( '_secure'=>$loadFromSSL))?>giftcard_code/"+code+"/giftcard_amount/"+amount);
        return false;
    }
</script>
