<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php //$posts = $this->getPostCollection();
$posts = Mage::getResourceModel('wordpress/post_collection');
/* print_r($posts->getData());
exit; */
$display_no_of_posts=0;
?>
<?php if (count($posts) > 0): ?>
<script type="text/javascript">// <![CDATA[
//&lt;![CDATA[
		jQuery(function ($) {
$('.responsiveGallery-wrapper').responsiveGallery({
	animatDuration: 400,
	$btn_prev: $('.responsiveGallery-btn_prev'),
	$btn_next: $('.responsiveGallery-btn_next')
});
		});
//]]&gt;
// ]]></script>

<div class="main-title">
          <h3> See our latest blog post</h3>
 </div>
    <div class="row">
		<?php foreach($posts as $post): ?>
			<?php $featuredImage = $post->getFeaturedImage(); ?>
			
			<?php $featuredImageobj = $post->getImages()->getFirstItem()->getData(); 
			//if(!empty($featuredImageobj)){			$featuredImageobj->getGuid();}
			?>
			<?php if(!empty($featuredImageobj)): 
                  if($display_no_of_posts < 3):
                  	$display_no_of_posts++;
                    $timestamp=strtotime($post->getPostDate());
                    $day = date('F d,Y', $timestamp);
                    //$month = date('M', $timestamp);
			     ?>

			        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
			            <div class="row">
			                <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5"> 
                               <a href="<?php echo $post->getPermalink() ?>" class="responsivGallery-link"><img src="<?php echo $featuredImageobj['guid'] ?>" alt="" ></a>
			                </div>
			                 <div class="col-xs-7 col-sm-7 col-md-7 col-lg-7"> 
			                 <?php
			                  echo $day."<br>";
                             ?>

			                 <a id="blog-post-title" href="<?php echo $post->getPermalink() ?>"><?php echo $post->getPostTitle() ?></a>
			                 </div>
			            </div>
			        </div>
       
			<?php endif;
                  endif;   
			 ?>
		<?php endforeach; ?>
    </div>

<?php endif; ?>

