<style>
<?php if(Mage::getStoreConfigFlag('giftcards/default/split_amount')):?>
.card-amount {
    border-bottom: solid 1px;
    cursor: pointer;
}
<?php endif;?>
#edit-div {
    display: none;
}
#apply-btn img {
    vertical-align: middle !important;
    margin-top: 5px;
    margin-left: 3px;
    cursor: pointer;
}
</style>

<?php $oGiftCardSession = Mage::getSingleton('giftcards/session'); ?>
<?php $loadFromSSL = $_SERVER['SERVER_PORT']==443?true:false; ?>
<?php $isGiftCard = $this->isGiftCard(); ?>

<div class="discount">
    <div class="sp-methods">
        <form method="post" action="<?php echo $this->getUrl('giftcards/cart/giftcardActive'); ?>" id="giftcardAgree">
            <div class="input-box">
                <input type="checkbox" value="1" name="giftcard_use" id="giftcard_use" class="checkbox" onclick="agreeMethod.save();" <?php echo $oGiftCardSession->getActive() ? 'checked="checked"' : '' ?>>
                <label for="giftcard_use"><?php echo $this->__('Gift Cards'); ?></label>
            </div>
        </form>
    </div>
<?php if(!$isGiftCard) : ?>
    <?php if($oGiftCardSession->getActive()): ?>
    <div class="discount-form giftcard-payment-method">
        <form method="post" action="<?php echo $this->getUrl('giftcards/cart/activateGiftCard'); ?>" id="activateGiftCard">
            <label for="giftcard_code"><?php echo $this->__('Redeem and use your Gift Card now'); ?></label>
            <div class="input-box">
                <input value="" name="giftcard_code" id="giftcard_code" class="input-text">
            </div>
            <div class="buttons-set">
                <button value="<?php echo $this->__('Apply') ?>" onclick="activateGiftCard.save()" class="button"
                        title="Apply" type="button" style="float: left;"><span><span><?php echo $this->__('Apply') ?></span></span>
                </button>
            </div>
        </form>

        <?php $currencySymbol = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); $temp = 0; ?>
        <?php if($oGiftCardSession->getActive()) {
            echo '<br/>';
            foreach($oGiftCardSession->getFrontOptions() as $k => $v)
            {
                if($temp) {
                    echo '<br/><br/>';
                }
                // echo '<b>'.$currencySymbol.$v['applied'].' '.$this->__('applied from Gift Card').' '.$v['code'].'.</b><br/>';
                echo '<div id="edit-div""><input id="edit-card-amount-'.$k.'" style="width:50px;text-align:right;" value="'. $v['applied']. '" />';
                echo '<span id="apply-btn"><a onclick="applyAmount('.$k.'); return false;"><img src="'.$this->getSkinUrl('images/giftcard_apply.gif').'" alt=""></a></span>';
                echo '</div><b><span id="card-amount" class="card-amount" onclick="editAmount()">'.$currencySymbol.$v['applied'].'</span> '.$this->__('applied from Gift Card').' '.$v['code'].'.';
                echo '<input id="edit-card-code-'.$k.'" style="display:none;" value="'.$v['code'].'">';
                echo '</b><br/>';
                echo $this->__('Remaining card balance').': '.$currencySymbol.$v['remaining'].'. (<a href="#" onclick="deActivateGiftCard.deactivate('.$k.');">'.$this->__('Remove').'</a>)';
                $temp = 1;
            }
        }
        ?>
    </div>

    <?php endif;?>
<?php else : ?>    
    <?php echo $this->__('Gift cards cannot be used to purchase gift cards'); ?>
<?php endif; ?>

</div>

<script type="text/javascript">
    function editAmount(){
        <?php if(Mage::getStoreConfigFlag('giftcards/default/split_amount')):?>
        $('card-amount').hide();
        $('edit-div').setStyle({display : 'inline-flex'});
        <?php endif;?>
        return true;
    }

    function applyAmount(id){
        var code = $('edit-card-code-'+id).value;
        var amount = $('edit-card-amount-'+id).value;
        if (checkout.loadWaiting!=false) return;
        checkout.setLoadWaiting('payment');
        var request = new Ajax.Request(
            deActivateGiftCard.saveUrl,
            {
                method:'post',
                onComplete: deActivateGiftCard.onComplete,
                onFailure: checkout.ajaxFailure.bind(checkout),
                parameters: 'id=' + id,
                onSuccess: function() {
                    var request = new Ajax.Request(
                        activateGiftCard.saveUrl,
                        {
                            method:'post',
                            onComplete: activateGiftCard.onComplete,
                            onSuccess: activateGiftCard.onSave,
                            onFailure: checkout.ajaxFailure.bind(checkout),
                            parameters: {giftcard_code : code, giftcard_amount: amount}
                        }
                     );
                }
            }
        );
    }
</script>

